//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDash.JDashRegistrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRegistrationInfo", Namespace="http://schemas.datacontract.org/2004/07/JDash.ProductRegistration")]
    [System.SerializableAttribute()]
    public partial class ProductRegistrationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentRegistryLicenseKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkstationIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControlData {
            get {
                return this.ControlDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlDataField, value) != true)) {
                    this.ControlDataField = value;
                    this.RaisePropertyChanged("ControlData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentRegistryLicenseKey {
            get {
                return this.CurrentRegistryLicenseKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentRegistryLicenseKeyField, value) != true)) {
                    this.CurrentRegistryLicenseKeyField = value;
                    this.RaisePropertyChanged("CurrentRegistryLicenseKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkstationID {
            get {
                return this.WorkstationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkstationIDField, value) != true)) {
                    this.WorkstationIDField = value;
                    this.RaisePropertyChanged("WorkstationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRegistrationInfoRet", Namespace="http://schemas.datacontract.org/2004/07/JDash.ProductRegistration")]
    [System.SerializableAttribute()]
    public partial class ProductRegistrationInfoRet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenceKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegistrationCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControlResult {
            get {
                return this.ControlResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlResultField, value) != true)) {
                    this.ControlResultField = value;
                    this.RaisePropertyChanged("ControlResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenceKey {
            get {
                return this.LicenceKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenceKeyField, value) != true)) {
                    this.LicenceKeyField = value;
                    this.RaisePropertyChanged("LicenceKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrationCount {
            get {
                return this.RegistrationCountField;
            }
            set {
                if ((this.RegistrationCountField.Equals(value) != true)) {
                    this.RegistrationCountField = value;
                    this.RaisePropertyChanged("RegistrationCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JDashRegistrationService.IJDashRegistrationService")]
    public interface IJDashRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJDashRegistrationService/RegisterProduct", ReplyAction="http://tempuri.org/IJDashRegistrationService/RegisterProductResponse")]
        JDash.JDashRegistrationService.ProductRegistrationInfoRet RegisterProduct(JDash.JDashRegistrationService.ProductRegistrationInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJDashRegistrationService/Test", ReplyAction="http://tempuri.org/IJDashRegistrationService/TestResponse")]
        bool Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJDashRegistrationServiceChannel : JDash.JDashRegistrationService.IJDashRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JDashRegistrationServiceClient : System.ServiceModel.ClientBase<JDash.JDashRegistrationService.IJDashRegistrationService>, JDash.JDashRegistrationService.IJDashRegistrationService {
        
        public JDashRegistrationServiceClient() {
        }
        
        public JDashRegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JDashRegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JDashRegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JDashRegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JDash.JDashRegistrationService.ProductRegistrationInfoRet RegisterProduct(JDash.JDashRegistrationService.ProductRegistrationInfo info) {
            return base.Channel.RegisterProduct(info);
        }
        
        public bool Test() {
            return base.Channel.Test();
        }
    }
}
