//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DashModel", "FK_Dashlets_Dashboard", "Dashboard", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.SqlProvider.Models.Dashboard), "Dashlet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.SqlProvider.Models.Dashlet), true)]
[assembly: EdmRelationshipAttribute("DashModel", "FK_TagRelation_Dashboard", "Dashboard", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.SqlProvider.Models.Dashboard), "TagRelation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.SqlProvider.Models.TagRelation), true)]
[assembly: EdmRelationshipAttribute("DashModel", "FK_Dashlets_DashletModules", "DashletModule", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.SqlProvider.Models.DashletModule), "Dashlet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.SqlProvider.Models.Dashlet), true)]
[assembly: EdmRelationshipAttribute("DashModel", "FK_TagRelation_Dashlets", "Dashlet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.SqlProvider.Models.Dashlet), "TagRelation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.SqlProvider.Models.TagRelation), true)]
[assembly: EdmRelationshipAttribute("DashModel", "FK_TagRelation_DashletModule", "DashletModule", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.SqlProvider.Models.DashletModule), "TagRelation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.SqlProvider.Models.TagRelation), true)]
[assembly: EdmRelationshipAttribute("DashModel", "FK_TagRelation_Tags", "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.SqlProvider.Models.Tag), "TagRelation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.SqlProvider.Models.TagRelation), true)]

#endregion

namespace JDash.SqlProvider.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DashEntity : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DashEntity object using the connection string found in the 'DashEntity' section of the application configuration file.
        /// </summary>
        public DashEntity() : base("name=DashEntity", "DashEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DashEntity object.
        /// </summary>
        public DashEntity(string connectionString) : base(connectionString, "DashEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DashEntity object.
        /// </summary>
        public DashEntity(EntityConnection connection) : base(connection, "DashEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dashboard> Dashboard
        {
            get
            {
                if ((_Dashboard == null))
                {
                    _Dashboard = base.CreateObjectSet<Dashboard>("Dashboard");
                }
                return _Dashboard;
            }
        }
        private ObjectSet<Dashboard> _Dashboard;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dashlet> Dashlet
        {
            get
            {
                if ((_Dashlet == null))
                {
                    _Dashlet = base.CreateObjectSet<Dashlet>("Dashlet");
                }
                return _Dashlet;
            }
        }
        private ObjectSet<Dashlet> _Dashlet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DashletModule> DashletModule
        {
            get
            {
                if ((_DashletModule == null))
                {
                    _DashletModule = base.CreateObjectSet<DashletModule>("DashletModule");
                }
                return _DashletModule;
            }
        }
        private ObjectSet<DashletModule> _DashletModule;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityAuth> EntityAuth
        {
            get
            {
                if ((_EntityAuth == null))
                {
                    _EntityAuth = base.CreateObjectSet<EntityAuth>("EntityAuth");
                }
                return _EntityAuth;
            }
        }
        private ObjectSet<EntityAuth> _EntityAuth;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tag
        {
            get
            {
                if ((_Tag == null))
                {
                    _Tag = base.CreateObjectSet<Tag>("Tag");
                }
                return _Tag;
            }
        }
        private ObjectSet<Tag> _Tag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TagRelation> TagRelation
        {
            get
            {
                if ((_TagRelation == null))
                {
                    _TagRelation = base.CreateObjectSet<TagRelation>("TagRelation");
                }
                return _TagRelation;
            }
        }
        private ObjectSet<TagRelation> _TagRelation;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dashboard EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDashboard(Dashboard dashboard)
        {
            base.AddObject("Dashboard", dashboard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dashlet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDashlet(Dashlet dashlet)
        {
            base.AddObject("Dashlet", dashlet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DashletModule EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDashletModule(DashletModule dashletModule)
        {
            base.AddObject("DashletModule", dashletModule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntityAuth EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntityAuth(EntityAuth entityAuth)
        {
            base.AddObject("EntityAuth", entityAuth);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTag(Tag tag)
        {
            base.AddObject("Tag", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TagRelation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTagRelation(TagRelation tagRelation)
        {
            base.AddObject("TagRelation", tagRelation);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DashModel", Name="Dashboard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dashboard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dashboard object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="layout">Initial value of the layout property.</param>
        /// <param name="createdBy">Initial value of the createdBy property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static Dashboard CreateDashboard(global::System.Int32 id, global::System.String layout, global::System.String createdBy, global::System.DateTime created)
        {
            Dashboard dashboard = new Dashboard();
            dashboard.id = id;
            dashboard.layout = layout;
            dashboard.createdBy = createdBy;
            dashboard.created = created;
            return dashboard;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String layout
        {
            get
            {
                return _layout;
            }
            set
            {
                OnlayoutChanging(value);
                ReportPropertyChanging("layout");
                _layout = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("layout");
                OnlayoutChanged();
            }
        }
        private global::System.String _layout;
        partial void OnlayoutChanging(global::System.String value);
        partial void OnlayoutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String config
        {
            get
            {
                return _config;
            }
            set
            {
                OnconfigChanging(value);
                ReportPropertyChanging("config");
                _config = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("config");
                OnconfigChanged();
            }
        }
        private global::System.String _config;
        partial void OnconfigChanging(global::System.String value);
        partial void OnconfigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String paneConfig
        {
            get
            {
                return _paneConfig;
            }
            set
            {
                OnpaneConfigChanging(value);
                ReportPropertyChanging("paneConfig");
                _paneConfig = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("paneConfig");
                OnpaneConfigChanged();
            }
        }
        private global::System.String _paneConfig;
        partial void OnpaneConfigChanging(global::System.String value);
        partial void OnpaneConfigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String style
        {
            get
            {
                return _style;
            }
            set
            {
                OnstyleChanging(value);
                ReportPropertyChanging("style");
                _style = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("style");
                OnstyleChanged();
            }
        }
        private global::System.String _style;
        partial void OnstyleChanging(global::System.String value);
        partial void OnstyleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cls
        {
            get
            {
                return _cls;
            }
            set
            {
                OnclsChanging(value);
                ReportPropertyChanging("cls");
                _cls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cls");
                OnclsChanged();
            }
        }
        private global::System.String _cls;
        partial void OnclsChanging(global::System.String value);
        partial void OnclsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attr
        {
            get
            {
                return _attr;
            }
            set
            {
                OnattrChanging(value);
                ReportPropertyChanging("attr");
                _attr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attr");
                OnattrChanged();
            }
        }
        private global::System.String _attr;
        partial void OnattrChanging(global::System.String value);
        partial void OnattrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String groupName
        {
            get
            {
                return _groupName;
            }
            set
            {
                OngroupNameChanging(value);
                ReportPropertyChanging("groupName");
                _groupName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("groupName");
                OngroupNameChanged();
            }
        }
        private global::System.String _groupName;
        partial void OngroupNameChanging(global::System.String value);
        partial void OngroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private global::System.String _modifiedBy;
        partial void OnmodifiedByChanging(global::System.String value);
        partial void OnmodifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sharedBy
        {
            get
            {
                return _sharedBy;
            }
            set
            {
                OnsharedByChanging(value);
                ReportPropertyChanging("sharedBy");
                _sharedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sharedBy");
                OnsharedByChanged();
            }
        }
        private global::System.String _sharedBy;
        partial void OnsharedByChanging(global::System.String value);
        partial void OnsharedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified;
        partial void OnmodifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> shared
        {
            get
            {
                return _shared;
            }
            set
            {
                OnsharedChanging(value);
                ReportPropertyChanging("shared");
                _shared = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("shared");
                OnsharedChanged();
            }
        }
        private Nullable<global::System.DateTime> _shared;
        partial void OnsharedChanging(Nullable<global::System.DateTime> value);
        partial void OnsharedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userData
        {
            get
            {
                return _userData;
            }
            set
            {
                OnuserDataChanging(value);
                ReportPropertyChanging("userData");
                _userData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userData");
                OnuserDataChanged();
            }
        }
        private global::System.String _userData;
        partial void OnuserDataChanging(global::System.String value);
        partial void OnuserDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> viewOrder
        {
            get
            {
                return _viewOrder;
            }
            set
            {
                OnviewOrderChanging(value);
                ReportPropertyChanging("viewOrder");
                _viewOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viewOrder");
                OnviewOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _viewOrder;
        partial void OnviewOrderChanging(Nullable<global::System.Int32> value);
        partial void OnviewOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> groupOrder
        {
            get
            {
                return _groupOrder;
            }
            set
            {
                OngroupOrderChanging(value);
                ReportPropertyChanging("groupOrder");
                _groupOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupOrder");
                OngroupOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _groupOrder;
        partial void OngroupOrderChanging(Nullable<global::System.Int32> value);
        partial void OngroupOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty1
        {
            get
            {
                return _UserProperty1;
            }
            set
            {
                OnUserProperty1Changing(value);
                ReportPropertyChanging("UserProperty1");
                _UserProperty1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty1");
                OnUserProperty1Changed();
            }
        }
        private global::System.String _UserProperty1;
        partial void OnUserProperty1Changing(global::System.String value);
        partial void OnUserProperty1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty2
        {
            get
            {
                return _UserProperty2;
            }
            set
            {
                OnUserProperty2Changing(value);
                ReportPropertyChanging("UserProperty2");
                _UserProperty2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty2");
                OnUserProperty2Changed();
            }
        }
        private global::System.String _UserProperty2;
        partial void OnUserProperty2Changing(global::System.String value);
        partial void OnUserProperty2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty3
        {
            get
            {
                return _UserProperty3;
            }
            set
            {
                OnUserProperty3Changing(value);
                ReportPropertyChanging("UserProperty3");
                _UserProperty3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty3");
                OnUserProperty3Changed();
            }
        }
        private global::System.String _UserProperty3;
        partial void OnUserProperty3Changing(global::System.String value);
        partial void OnUserProperty3Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_Dashlets_Dashboard", "Dashlet")]
        public EntityCollection<Dashlet> Dashlet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dashlet>("DashModel.FK_Dashlets_Dashboard", "Dashlet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dashlet>("DashModel.FK_Dashlets_Dashboard", "Dashlet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_TagRelation_Dashboard", "TagRelation")]
        public EntityCollection<TagRelation> TagRelation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagRelation>("DashModel.FK_TagRelation_Dashboard", "TagRelation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagRelation>("DashModel.FK_TagRelation_Dashboard", "TagRelation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DashModel", Name="Dashlet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dashlet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dashlet object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="dashboardId">Initial value of the dashboardId property.</param>
        /// <param name="dashletModuleId">Initial value of the dashletModuleId property.</param>
        /// <param name="position">Initial value of the position property.</param>
        /// <param name="createdBy">Initial value of the createdBy property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static Dashlet CreateDashlet(global::System.Int32 id, global::System.Int32 dashboardId, global::System.Int32 dashletModuleId, global::System.String position, global::System.String createdBy, global::System.DateTime created)
        {
            Dashlet dashlet = new Dashlet();
            dashlet.id = id;
            dashlet.dashboardId = dashboardId;
            dashlet.dashletModuleId = dashletModuleId;
            dashlet.position = position;
            dashlet.createdBy = createdBy;
            dashlet.created = created;
            return dashlet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dashboardId
        {
            get
            {
                return _dashboardId;
            }
            set
            {
                OndashboardIdChanging(value);
                ReportPropertyChanging("dashboardId");
                _dashboardId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dashboardId");
                OndashboardIdChanged();
            }
        }
        private global::System.Int32 _dashboardId;
        partial void OndashboardIdChanging(global::System.Int32 value);
        partial void OndashboardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dashletModuleId
        {
            get
            {
                return _dashletModuleId;
            }
            set
            {
                OndashletModuleIdChanging(value);
                ReportPropertyChanging("dashletModuleId");
                _dashletModuleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dashletModuleId");
                OndashletModuleIdChanged();
            }
        }
        private global::System.Int32 _dashletModuleId;
        partial void OndashletModuleIdChanging(global::System.Int32 value);
        partial void OndashletModuleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String config
        {
            get
            {
                return _config;
            }
            set
            {
                OnconfigChanging(value);
                ReportPropertyChanging("config");
                _config = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("config");
                OnconfigChanged();
            }
        }
        private global::System.String _config;
        partial void OnconfigChanging(global::System.String value);
        partial void OnconfigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String paneConfig
        {
            get
            {
                return _paneConfig;
            }
            set
            {
                OnpaneConfigChanging(value);
                ReportPropertyChanging("paneConfig");
                _paneConfig = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("paneConfig");
                OnpaneConfigChanged();
            }
        }
        private global::System.String _paneConfig;
        partial void OnpaneConfigChanging(global::System.String value);
        partial void OnpaneConfigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String position
        {
            get
            {
                return _position;
            }
            set
            {
                OnpositionChanging(value);
                ReportPropertyChanging("position");
                _position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("position");
                OnpositionChanged();
            }
        }
        private global::System.String _position;
        partial void OnpositionChanging(global::System.String value);
        partial void OnpositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String style
        {
            get
            {
                return _style;
            }
            set
            {
                OnstyleChanging(value);
                ReportPropertyChanging("style");
                _style = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("style");
                OnstyleChanged();
            }
        }
        private global::System.String _style;
        partial void OnstyleChanging(global::System.String value);
        partial void OnstyleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cls
        {
            get
            {
                return _cls;
            }
            set
            {
                OnclsChanging(value);
                ReportPropertyChanging("cls");
                _cls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cls");
                OnclsChanged();
            }
        }
        private global::System.String _cls;
        partial void OnclsChanging(global::System.String value);
        partial void OnclsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attr
        {
            get
            {
                return _attr;
            }
            set
            {
                OnattrChanging(value);
                ReportPropertyChanging("attr");
                _attr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attr");
                OnattrChanged();
            }
        }
        private global::System.String _attr;
        partial void OnattrChanging(global::System.String value);
        partial void OnattrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String groupName
        {
            get
            {
                return _groupName;
            }
            set
            {
                OngroupNameChanging(value);
                ReportPropertyChanging("groupName");
                _groupName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("groupName");
                OngroupNameChanged();
            }
        }
        private global::System.String _groupName;
        partial void OngroupNameChanging(global::System.String value);
        partial void OngroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private global::System.String _modifiedBy;
        partial void OnmodifiedByChanging(global::System.String value);
        partial void OnmodifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sharedBy
        {
            get
            {
                return _sharedBy;
            }
            set
            {
                OnsharedByChanging(value);
                ReportPropertyChanging("sharedBy");
                _sharedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sharedBy");
                OnsharedByChanged();
            }
        }
        private global::System.String _sharedBy;
        partial void OnsharedByChanging(global::System.String value);
        partial void OnsharedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified;
        partial void OnmodifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> shared
        {
            get
            {
                return _shared;
            }
            set
            {
                OnsharedChanging(value);
                ReportPropertyChanging("shared");
                _shared = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("shared");
                OnsharedChanged();
            }
        }
        private Nullable<global::System.DateTime> _shared;
        partial void OnsharedChanging(Nullable<global::System.DateTime> value);
        partial void OnsharedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userData
        {
            get
            {
                return _userData;
            }
            set
            {
                OnuserDataChanging(value);
                ReportPropertyChanging("userData");
                _userData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userData");
                OnuserDataChanged();
            }
        }
        private global::System.String _userData;
        partial void OnuserDataChanging(global::System.String value);
        partial void OnuserDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty1
        {
            get
            {
                return _UserProperty1;
            }
            set
            {
                OnUserProperty1Changing(value);
                ReportPropertyChanging("UserProperty1");
                _UserProperty1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty1");
                OnUserProperty1Changed();
            }
        }
        private global::System.String _UserProperty1;
        partial void OnUserProperty1Changing(global::System.String value);
        partial void OnUserProperty1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty2
        {
            get
            {
                return _UserProperty2;
            }
            set
            {
                OnUserProperty2Changing(value);
                ReportPropertyChanging("UserProperty2");
                _UserProperty2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty2");
                OnUserProperty2Changed();
            }
        }
        private global::System.String _UserProperty2;
        partial void OnUserProperty2Changing(global::System.String value);
        partial void OnUserProperty2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty3
        {
            get
            {
                return _UserProperty3;
            }
            set
            {
                OnUserProperty3Changing(value);
                ReportPropertyChanging("UserProperty3");
                _UserProperty3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty3");
                OnUserProperty3Changed();
            }
        }
        private global::System.String _UserProperty3;
        partial void OnUserProperty3Changing(global::System.String value);
        partial void OnUserProperty3Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_Dashlets_Dashboard", "Dashboard")]
        public Dashboard Dashboard
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("DashModel.FK_Dashlets_Dashboard", "Dashboard").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("DashModel.FK_Dashlets_Dashboard", "Dashboard").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dashboard> DashboardReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("DashModel.FK_Dashlets_Dashboard", "Dashboard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dashboard>("DashModel.FK_Dashlets_Dashboard", "Dashboard", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_Dashlets_DashletModules", "DashletModule")]
        public DashletModule DashletModule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("DashModel.FK_Dashlets_DashletModules", "DashletModule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("DashModel.FK_Dashlets_DashletModules", "DashletModule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DashletModule> DashletModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("DashModel.FK_Dashlets_DashletModules", "DashletModule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DashletModule>("DashModel.FK_Dashlets_DashletModules", "DashletModule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_TagRelation_Dashlets", "TagRelation")]
        public EntityCollection<TagRelation> TagRelation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagRelation>("DashModel.FK_TagRelation_Dashlets", "TagRelation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagRelation>("DashModel.FK_TagRelation_Dashlets", "TagRelation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DashModel", Name="DashletModule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DashletModule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DashletModule object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="path">Initial value of the path property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="config">Initial value of the config property.</param>
        /// <param name="paneConfig">Initial value of the paneConfig property.</param>
        /// <param name="dashletConfig">Initial value of the dashletConfig property.</param>
        /// <param name="createdBy">Initial value of the createdBy property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static DashletModule CreateDashletModule(global::System.Int32 id, global::System.String path, global::System.String title, global::System.String config, global::System.String paneConfig, global::System.String dashletConfig, global::System.String createdBy, global::System.DateTime created)
        {
            DashletModule dashletModule = new DashletModule();
            dashletModule.id = id;
            dashletModule.path = path;
            dashletModule.title = title;
            dashletModule.config = config;
            dashletModule.paneConfig = paneConfig;
            dashletModule.dashletConfig = dashletConfig;
            dashletModule.createdBy = createdBy;
            dashletModule.created = created;
            return dashletModule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String path
        {
            get
            {
                return _path;
            }
            set
            {
                OnpathChanging(value);
                ReportPropertyChanging("path");
                _path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("path");
                OnpathChanged();
            }
        }
        private global::System.String _path;
        partial void OnpathChanging(global::System.String value);
        partial void OnpathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String config
        {
            get
            {
                return _config;
            }
            set
            {
                OnconfigChanging(value);
                ReportPropertyChanging("config");
                _config = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("config");
                OnconfigChanged();
            }
        }
        private global::System.String _config;
        partial void OnconfigChanging(global::System.String value);
        partial void OnconfigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String paneConfig
        {
            get
            {
                return _paneConfig;
            }
            set
            {
                OnpaneConfigChanging(value);
                ReportPropertyChanging("paneConfig");
                _paneConfig = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("paneConfig");
                OnpaneConfigChanged();
            }
        }
        private global::System.String _paneConfig;
        partial void OnpaneConfigChanging(global::System.String value);
        partial void OnpaneConfigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dashletConfig
        {
            get
            {
                return _dashletConfig;
            }
            set
            {
                OndashletConfigChanging(value);
                ReportPropertyChanging("dashletConfig");
                _dashletConfig = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dashletConfig");
                OndashletConfigChanged();
            }
        }
        private global::System.String _dashletConfig;
        partial void OndashletConfigChanging(global::System.String value);
        partial void OndashletConfigChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String style
        {
            get
            {
                return _style;
            }
            set
            {
                OnstyleChanging(value);
                ReportPropertyChanging("style");
                _style = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("style");
                OnstyleChanged();
            }
        }
        private global::System.String _style;
        partial void OnstyleChanging(global::System.String value);
        partial void OnstyleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cls
        {
            get
            {
                return _cls;
            }
            set
            {
                OnclsChanging(value);
                ReportPropertyChanging("cls");
                _cls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cls");
                OnclsChanged();
            }
        }
        private global::System.String _cls;
        partial void OnclsChanging(global::System.String value);
        partial void OnclsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attr
        {
            get
            {
                return _attr;
            }
            set
            {
                OnattrChanging(value);
                ReportPropertyChanging("attr");
                _attr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attr");
                OnattrChanged();
            }
        }
        private global::System.String _attr;
        partial void OnattrChanging(global::System.String value);
        partial void OnattrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private global::System.String _modifiedBy;
        partial void OnmodifiedByChanging(global::System.String value);
        partial void OnmodifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sharedBy
        {
            get
            {
                return _sharedBy;
            }
            set
            {
                OnsharedByChanging(value);
                ReportPropertyChanging("sharedBy");
                _sharedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sharedBy");
                OnsharedByChanged();
            }
        }
        private global::System.String _sharedBy;
        partial void OnsharedByChanging(global::System.String value);
        partial void OnsharedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified;
        partial void OnmodifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> shared
        {
            get
            {
                return _shared;
            }
            set
            {
                OnsharedChanging(value);
                ReportPropertyChanging("shared");
                _shared = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("shared");
                OnsharedChanged();
            }
        }
        private Nullable<global::System.DateTime> _shared;
        partial void OnsharedChanging(Nullable<global::System.DateTime> value);
        partial void OnsharedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String groupName
        {
            get
            {
                return _groupName;
            }
            set
            {
                OngroupNameChanging(value);
                ReportPropertyChanging("groupName");
                _groupName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("groupName");
                OngroupNameChanged();
            }
        }
        private global::System.String _groupName;
        partial void OngroupNameChanging(global::System.String value);
        partial void OngroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userData
        {
            get
            {
                return _userData;
            }
            set
            {
                OnuserDataChanging(value);
                ReportPropertyChanging("userData");
                _userData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userData");
                OnuserDataChanged();
            }
        }
        private global::System.String _userData;
        partial void OnuserDataChanging(global::System.String value);
        partial void OnuserDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> viewOrder
        {
            get
            {
                return _viewOrder;
            }
            set
            {
                OnviewOrderChanging(value);
                ReportPropertyChanging("viewOrder");
                _viewOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viewOrder");
                OnviewOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _viewOrder;
        partial void OnviewOrderChanging(Nullable<global::System.Int32> value);
        partial void OnviewOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> groupOrder
        {
            get
            {
                return _groupOrder;
            }
            set
            {
                OngroupOrderChanging(value);
                ReportPropertyChanging("groupOrder");
                _groupOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupOrder");
                OngroupOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _groupOrder;
        partial void OngroupOrderChanging(Nullable<global::System.Int32> value);
        partial void OngroupOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty1
        {
            get
            {
                return _UserProperty1;
            }
            set
            {
                OnUserProperty1Changing(value);
                ReportPropertyChanging("UserProperty1");
                _UserProperty1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty1");
                OnUserProperty1Changed();
            }
        }
        private global::System.String _UserProperty1;
        partial void OnUserProperty1Changing(global::System.String value);
        partial void OnUserProperty1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty2
        {
            get
            {
                return _UserProperty2;
            }
            set
            {
                OnUserProperty2Changing(value);
                ReportPropertyChanging("UserProperty2");
                _UserProperty2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty2");
                OnUserProperty2Changed();
            }
        }
        private global::System.String _UserProperty2;
        partial void OnUserProperty2Changing(global::System.String value);
        partial void OnUserProperty2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserProperty3
        {
            get
            {
                return _UserProperty3;
            }
            set
            {
                OnUserProperty3Changing(value);
                ReportPropertyChanging("UserProperty3");
                _UserProperty3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserProperty3");
                OnUserProperty3Changed();
            }
        }
        private global::System.String _UserProperty3;
        partial void OnUserProperty3Changing(global::System.String value);
        partial void OnUserProperty3Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_Dashlets_DashletModules", "Dashlet")]
        public EntityCollection<Dashlet> Dashlet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dashlet>("DashModel.FK_Dashlets_DashletModules", "Dashlet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dashlet>("DashModel.FK_Dashlets_DashletModules", "Dashlet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_TagRelation_DashletModule", "TagRelation")]
        public EntityCollection<TagRelation> TagRelation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagRelation>("DashModel.FK_TagRelation_DashletModule", "TagRelation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagRelation>("DashModel.FK_TagRelation_DashletModule", "TagRelation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DashModel", Name="EntityAuth")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityAuth : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityAuth object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="entityType">Initial value of the entityType property.</param>
        /// <param name="entityId">Initial value of the entityId property.</param>
        /// <param name="roleOrUser">Initial value of the roleOrUser property.</param>
        /// <param name="permission">Initial value of the permission property.</param>
        /// <param name="authType">Initial value of the authType property.</param>
        public static EntityAuth CreateEntityAuth(global::System.Int32 id, global::System.String entityType, global::System.Int32 entityId, global::System.String roleOrUser, global::System.String permission, global::System.String authType)
        {
            EntityAuth entityAuth = new EntityAuth();
            entityAuth.id = id;
            entityAuth.entityType = entityType;
            entityAuth.entityId = entityId;
            entityAuth.roleOrUser = roleOrUser;
            entityAuth.permission = permission;
            entityAuth.authType = authType;
            return entityAuth;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String entityType
        {
            get
            {
                return _entityType;
            }
            set
            {
                OnentityTypeChanging(value);
                ReportPropertyChanging("entityType");
                _entityType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("entityType");
                OnentityTypeChanged();
            }
        }
        private global::System.String _entityType;
        partial void OnentityTypeChanging(global::System.String value);
        partial void OnentityTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 entityId
        {
            get
            {
                return _entityId;
            }
            set
            {
                OnentityIdChanging(value);
                ReportPropertyChanging("entityId");
                _entityId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entityId");
                OnentityIdChanged();
            }
        }
        private global::System.Int32 _entityId;
        partial void OnentityIdChanging(global::System.Int32 value);
        partial void OnentityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String roleOrUser
        {
            get
            {
                return _roleOrUser;
            }
            set
            {
                OnroleOrUserChanging(value);
                ReportPropertyChanging("roleOrUser");
                _roleOrUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("roleOrUser");
                OnroleOrUserChanged();
            }
        }
        private global::System.String _roleOrUser;
        partial void OnroleOrUserChanging(global::System.String value);
        partial void OnroleOrUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String permission
        {
            get
            {
                return _permission;
            }
            set
            {
                OnpermissionChanging(value);
                ReportPropertyChanging("permission");
                _permission = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("permission");
                OnpermissionChanged();
            }
        }
        private global::System.String _permission;
        partial void OnpermissionChanging(global::System.String value);
        partial void OnpermissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String authType
        {
            get
            {
                return _authType;
            }
            set
            {
                OnauthTypeChanging(value);
                ReportPropertyChanging("authType");
                _authType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("authType");
                OnauthTypeChanged();
            }
        }
        private global::System.String _authType;
        partial void OnauthTypeChanging(global::System.String value);
        partial void OnauthTypeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DashModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="tagName">Initial value of the tagName property.</param>
        public static Tag CreateTag(global::System.Int32 id, global::System.String tagName)
        {
            Tag tag = new Tag();
            tag.id = id;
            tag.tagName = tagName;
            return tag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tagName
        {
            get
            {
                return _tagName;
            }
            set
            {
                OntagNameChanging(value);
                ReportPropertyChanging("tagName");
                _tagName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tagName");
                OntagNameChanged();
            }
        }
        private global::System.String _tagName;
        partial void OntagNameChanging(global::System.String value);
        partial void OntagNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_TagRelation_Tags", "TagRelation")]
        public EntityCollection<TagRelation> TagRelation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagRelation>("DashModel.FK_TagRelation_Tags", "TagRelation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagRelation>("DashModel.FK_TagRelation_Tags", "TagRelation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DashModel", Name="TagRelation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TagRelation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TagRelation object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="tagId">Initial value of the tagId property.</param>
        /// <param name="controlId">Initial value of the controlId property.</param>
        /// <param name="controller">Initial value of the controller property.</param>
        public static TagRelation CreateTagRelation(global::System.Int32 id, global::System.Int32 tagId, global::System.Int32 controlId, global::System.String controller)
        {
            TagRelation tagRelation = new TagRelation();
            tagRelation.id = id;
            tagRelation.tagId = tagId;
            tagRelation.controlId = controlId;
            tagRelation.controller = controller;
            return tagRelation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tagId
        {
            get
            {
                return _tagId;
            }
            set
            {
                OntagIdChanging(value);
                ReportPropertyChanging("tagId");
                _tagId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tagId");
                OntagIdChanged();
            }
        }
        private global::System.Int32 _tagId;
        partial void OntagIdChanging(global::System.Int32 value);
        partial void OntagIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 controlId
        {
            get
            {
                return _controlId;
            }
            set
            {
                OncontrolIdChanging(value);
                ReportPropertyChanging("controlId");
                _controlId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("controlId");
                OncontrolIdChanged();
            }
        }
        private global::System.Int32 _controlId;
        partial void OncontrolIdChanging(global::System.Int32 value);
        partial void OncontrolIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String controller
        {
            get
            {
                return _controller;
            }
            set
            {
                OncontrollerChanging(value);
                ReportPropertyChanging("controller");
                _controller = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("controller");
                OncontrollerChanged();
            }
        }
        private global::System.String _controller;
        partial void OncontrollerChanging(global::System.String value);
        partial void OncontrollerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_TagRelation_Dashboard", "Dashboard")]
        public Dashboard Dashboard
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("DashModel.FK_TagRelation_Dashboard", "Dashboard").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("DashModel.FK_TagRelation_Dashboard", "Dashboard").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dashboard> DashboardReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("DashModel.FK_TagRelation_Dashboard", "Dashboard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dashboard>("DashModel.FK_TagRelation_Dashboard", "Dashboard", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_TagRelation_Dashlets", "Dashlet")]
        public Dashlet Dashlet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashlet>("DashModel.FK_TagRelation_Dashlets", "Dashlet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashlet>("DashModel.FK_TagRelation_Dashlets", "Dashlet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dashlet> DashletReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashlet>("DashModel.FK_TagRelation_Dashlets", "Dashlet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dashlet>("DashModel.FK_TagRelation_Dashlets", "Dashlet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_TagRelation_DashletModule", "DashletModule")]
        public DashletModule DashletModule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("DashModel.FK_TagRelation_DashletModule", "DashletModule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("DashModel.FK_TagRelation_DashletModule", "DashletModule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DashletModule> DashletModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("DashModel.FK_TagRelation_DashletModule", "DashletModule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DashletModule>("DashModel.FK_TagRelation_DashletModule", "DashletModule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DashModel", "FK_TagRelation_Tags", "Tag")]
        public Tag Tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("DashModel.FK_TagRelation_Tags", "Tag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("DashModel.FK_TagRelation_Tags", "Tag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tag> TagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("DashModel.FK_TagRelation_Tags", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tag>("DashModel.FK_TagRelation_Tags", "Tag", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
