using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Web.UI;


#if REGISTERED_VERSION
[assembly: AssemblyTitle("JDash for Asp.Net WebForms")]
#else
[assembly: AssemblyTitle("JDash for Asp.Net WebForms Trial")]
#endif
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Kalitte Inc.")]
[assembly: AssemblyProduct("JDash for Asp.Net WebForms")]
[assembly: AssemblyCopyright("© 2009-2014 Kalitte Inc.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: TagPrefix("JDash.WebForms", "jdash")]

[assembly: AssemblyVersion("4.3.0.0")]
[assembly: AssemblyFileVersion("4.3.0.0")]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]

/* JDash.WebForms EMBEDDED RESOURCES */

[assembly: WebResource("JDash.WebForms.resources.css.layout.builtin.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.css.layout.builtin-embedded.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.css.layout.layoutall.png", "image/png")]
[assembly: WebResource("JDash.WebForms.resources.img.logo.png", "image/png")]
[assembly: WebResource("JDash.WebForms.resources.jdash_debug.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ar.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ar.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_az.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_az.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ca.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ca.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_cs.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_cs.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_da.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_da.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_de.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_de.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_el.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_el.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_en-gb.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_en-us.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_es.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_es.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_es-es.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_fi.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_fi.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_fi-fi.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_fr.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_fr.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_fr-fr.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_he.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_he.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_he-il.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_hr.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_hr.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_hu.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_hu.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_it.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_it.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_it-it.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ja.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ja.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ja-jp.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_kk.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_kk.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ko.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ko.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ko-kr.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_nb.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_nb.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_nl.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_nl.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_nl-nl.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_pl.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_pl.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_pt.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_pt.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_pt_pt.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_pt-br.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_pt-pt.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ro.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ro.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ROOT.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ROOT.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ru.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_ru.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_sk.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_sk.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_sl.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_sl.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_sv.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_sv.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_th.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_th.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_tr.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_tr.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_tr-tr.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_zh.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_zh.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_zh_tw.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_zh-cn.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.jdash_zh-tw.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.language.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.language.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.tr.language.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.nls.tr.language.js.uncompressed.js", "text/javascript")]
[assembly: WebResource("JDash.WebForms.resources.themes.default.images.icons-18-black-pack.png", "image/png")]
[assembly: WebResource("JDash.WebForms.resources.themes.default.images.icons-18-white-pack.png", "image/png")]
[assembly: WebResource("JDash.WebForms.resources.themes.default.images.icons-36-black-pack.png", "image/png")]
[assembly: WebResource("JDash.WebForms.resources.themes.default.images.icons-36-white-pack.png", "image/png")]
[assembly: WebResource("JDash.WebForms.resources.themes.default.images.ui-icon-busy.gif", "image/gif")]
[assembly: WebResource("JDash.WebForms.resources.themes.default.main.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.themes.default.main-embedded.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.themes.default.old-embedded.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.css.font_awesome.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.css.font_awesome.min-embedded.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.css.font-awesome.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.css.font-awesome-embedded.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.FontAwesome.otf", "font/otf")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.fontawesome_webfont.eot", "application/vnd.ms-fontobject")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.fontawesome-webfont.eot", "font/eot")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.fontawesome-webfont.svg", "font/x-woff")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.fontawesome-webfont.svg", "image/svg+xml")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.fontawesome-webfont.ttf", "application/font/ttf")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.fontawesome-webfont.ttf", "font/ttf")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.fontawesome-webfont.woff", "font/woff")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.fonts.fontawesome-webfont.woff", "font/x-woff")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.images.ui-icon-busy.gif", "image/gif")]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.main.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("JDash.WebForms.resources.themes.flat.main-embedded.css", "text/css", PerformSubstitution = true)]