define({
    Ok: "Tamam",
    Yes: "Evet",
    No: "Hayır",
    Cancel: "İptal",
    Accept: "Kabul Et",
    Decline: "Reddet",
    Error: "Hata",
    Warning: "Uyarı",
    Information: "Bilgi",
    Confirmation: "Onaylama",
    Maximize: "Büyüt",   //?
    Collapse: "Küçült", //?
    Restore: "Eski Haline Getir", //?
    Expand: "Genişlet",
    Remove: "Kaldır",
    Seperator: "Ayraç",
    Share: "Paylaş",
    About: "Hakkında",
    EditSettings: "Düzenle",
    Options: "Ayarlar",
    MakeSticky: "Yapışkan Yap",
    MakeUnsticky: "Yağışkanlığı Kaldır",
    Reload: "Tekrar Yükle",
    RetreivingContent: "İçerik Alınıyor",
    Save: "Kaydet",
    Apply: "Uygula",
    Cancel: "İptal",
    ViewMode: "Görüntü Modu",
    InsideIFrame: "Iframe içerisinde",
    InsideCurrentDocument: "Mevcut döküman içerisinde",
    InvalidRSSSource: "Geçersiz RSS Kaynağı!",
    ValidatingRSSContent: "RSS doğrulanıyor ...",
    ShowHeadersOnly: "Sadece başlıkları göster",
    ShowFullContent: "Tüm içeriği göster",
    ShowContentSummary: "İçerik özetini göster",
    LimitFeeds: "Sonuçları sınırla",
    Unlimited: "Sınırsız",
    Refresh: "Güncelle",
    StartingDashboardLoad: "Dashboard yüklemesi başlatılıyor",
    CreatingLayout: "Dashboard düzeni oluşturuluyor",
    RetreivingDashlets: "Dashletler alınıyor",
    CreatingDashlets: "Dashlet'ler yaratılıyor",
    DashletsCreated: "Dashlet'ler yaratıldı",
    StartingDashlets: "Dashlet'ler başlatılıyor",
    DashletsStarted:"Dashlet'ler başlatıldı",
    ChangePositions: "Yer değiştir",
    SetBodyDrag: "Genel sürüklemeyi aç  ",
    SetHeaderDrag: "Başlıktan sürüklemeyi aç ",
    DisableTitleCollapse: "Başlıktan küçültmeyi kapat",
    EnableTitleCollapse: "Başlıktan küçültmeyi aç",
    AllGroups: "Tüm Gruplar",
    ConfirmMessage: "Emin misiniz?",
    ConfirmTitle: "Onay",
    Others: "Diğerleri",
    UnableToLoad: "İçerik yüklenemiyor!",
    FrameDimensions: "Çerçeve Boyutları",
    Width: "Genişlik",
    Heigth: "Yükseklik",
    Clone: "Kopyala"
});

