  CREATE SEQUENCE   "DASHBOARD_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 481 CACHE 20 NOORDER  NOCYCLE ;
   --end line--
    CREATE SEQUENCE   "DASHLETMODULE_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	--end line--
    CREATE SEQUENCE   "DASHLET_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
	--end line--
    CREATE SEQUENCE   "ENTITYAUTH_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	--end line--
    CREATE SEQUENCE   "TAGRELATION_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	--end line--
    CREATE SEQUENCE   "TAG_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	--end line--
   CREATE TABLE  "DASHBOARD"     ( "ID" NUMBER(10,0),   "TITLE" VARCHAR2(250 CHAR),   "LAYOUT" VARCHAR2(4000 BYTE),   "CONFIG" VARCHAR2(4000 BYTE),   "PANECONFIG" VARCHAR2(4000 BYTE),   "STYLE" VARCHAR2(4000 BYTE),   "CLS" VARCHAR2(4000 BYTE),   "ATTR" VARCHAR2(4000 BYTE),   "GROUPNAME" VARCHAR2(150 CHAR),   "DESCRIPTION" CLOB,   "CREATEDBY" VARCHAR2(150 CHAR),   "MODIFIEDBY" VARCHAR2(150 CHAR),   "SHAREDBY" VARCHAR2(150 CHAR),   "CREATED" DATE,   "MODIFIED" DATE,   "SHARED" DATE,   "USERDATA" VARCHAR2(4000 BYTE),   "VIEWORDER" NUMBER(10,0),   "GROUPORDER" NUMBER(10,0)    ) SEGMENT CREATION IMMEDIATE    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)   TABLESPACE "USERS"   LOB ("DESCRIPTION") STORE AS BASICFILE (   TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION    NOCACHE LOGGING    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
   --end line--
   CREATE TABLE  "DASHLET"     ( "ID" NUMBER(10,0),   "DASHBOARDID" NUMBER(10,0),   "DASHLETMODULEID" NUMBER(10,0),   "TITLE" VARCHAR2(255 CHAR),   "CONFIG" VARCHAR2(4000 BYTE),   "PANECONFIG" VARCHAR2(4000 BYTE),   "POSITION" VARCHAR2(4000 BYTE),   "STYLE" VARCHAR2(4000 BYTE),   "CLS" VARCHAR2(4000 BYTE),   "ATTR" VARCHAR2(4000 BYTE),   "GROUPNAME" VARCHAR2(150 CHAR),   "DESCRIPTION" CLOB,   "CREATEDBY" VARCHAR2(150 CHAR),   "MODIFIEDBY" VARCHAR2(150 CHAR),   "SHAREDBY" VARCHAR2(150 CHAR),   "CREATED" DATE,   "MODIFIED" DATE,   "SHARED" DATE,   "USERDATA" VARCHAR2(4000 BYTE)    ) SEGMENT CREATION IMMEDIATE    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)   TABLESPACE "USERS"   LOB ("DESCRIPTION") STORE AS BASICFILE (   TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION    NOCACHE LOGGING    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
   --end line--
   CREATE TABLE  "DASHLETMODULE"     ( "ID" NUMBER(10,0),   "PATH" CLOB,   "TITLE" VARCHAR2(255 CHAR),   "CONFIG" VARCHAR2(4000 BYTE),   "PANECONFIG" VARCHAR2(4000 BYTE),   "DASHLETCONFIG" VARCHAR2(4000 BYTE),   "STYLE" VARCHAR2(4000 BYTE),   "CLS" VARCHAR2(4000 BYTE),   "ATTR" VARCHAR2(4000 BYTE),   "DESCRIPTION" CLOB,   "CREATEDBY" VARCHAR2(150 CHAR),   "MODIFIEDBY" VARCHAR2(150 CHAR),   "SHAREDBY" VARCHAR2(150 CHAR),   "CREATED" DATE,   "MODIFIED" DATE,   "SHARED" DATE,   "GROUPNAME" VARCHAR2(150 CHAR),   "USERDATA" VARCHAR2(4000 BYTE),   "VIEWORDER" NUMBER(10,0),   "GROUPORDER" NUMBER(10,0)    ) SEGMENT CREATION IMMEDIATE    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)   TABLESPACE "USERS"   LOB ("PATH") STORE AS BASICFILE (   TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION    NOCACHE LOGGING    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))   LOB ("DESCRIPTION") STORE AS BASICFILE (   TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION    NOCACHE LOGGING    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
   --end line--
   CREATE TABLE  "ENTITYAUTH"     ( "ID" NUMBER(10,0),   "ENTITYTYPE" VARCHAR2(50 CHAR),   "ENTITYID" NUMBER(10,0),   "ROLEORUSER" VARCHAR2(50 CHAR),   "PERMISSION" VARCHAR2(50 CHAR),   "AUTHTYPE" VARCHAR2(50 CHAR)    ) SEGMENT CREATION IMMEDIATE    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)   TABLESPACE "USERS" ;
   --end line--
   CREATE TABLE  "TAG"     ( "ID" NUMBER(10,0),   "TAGNAME" VARCHAR2(150 CHAR)    ) SEGMENT CREATION IMMEDIATE    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)   TABLESPACE "USERS" ;
   --end line--
   CREATE TABLE  "TAGRELATION"     ( "ID" NUMBER(10,0),   "TAGID" NUMBER(10,0),   "CONTROLID" NUMBER(10,0),   "CONTROLLER" VARCHAR2(15 CHAR)    ) SEGMENT CREATION IMMEDIATE    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)   TABLESPACE "USERS" ;
   --end line--
   CREATE UNIQUE INDEX  "DASHLETMODULE_PK" ON  "DASHLETMODULE" ("ID") 
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS" ;
   --end line--
   CREATE UNIQUE INDEX  "DASHBOARD_PK" ON  "DASHBOARD" ("ID") 
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS" ;
   --end line--
   CREATE UNIQUE INDEX  "TAGRELATION_PK" ON  "TAGRELATION" ("ID") 
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS" ;
   --end line--
   CREATE UNIQUE INDEX  "TAG_PK" ON  "TAG" ("ID") 
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS" ;
   --end line--
   CREATE UNIQUE INDEX  "DASHLET_PK" ON  "DASHLET" ("ID") 
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS" ;
   --end line--
   CREATE UNIQUE INDEX  "ENTITYAUTH_PK" ON  "ENTITYAUTH" ("ID") 
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS" ;
   --end line--
   ALTER TABLE  "DASHLET" ADD CONSTRAINT "DASHLET_PK" PRIMARY KEY ("ID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS"  ENABLE;
   --end line--
   ALTER TABLE  "DASHLET" MODIFY ("ID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLET" MODIFY ("DASHBOARDID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLET" MODIFY ("DASHLETMODULEID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLET" MODIFY ("POSITION" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLET" MODIFY ("CREATEDBY" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLET" MODIFY ("CREATED" NOT NULL ENABLE);
 
   --end line--
   ALTER TABLE  "TAG" MODIFY ("ID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "TAG" MODIFY ("TAGNAME" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "TAG" ADD CONSTRAINT "TAG_PK" PRIMARY KEY ("ID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS"  ENABLE;
   --end line--
   ALTER TABLE  "DASHLETMODULE" ADD CONSTRAINT "DASHLETMODULE_PK" PRIMARY KEY ("ID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS"  ENABLE;
   --end line--
   ALTER TABLE  "DASHLETMODULE" MODIFY ("ID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLETMODULE" MODIFY ("PATH" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLETMODULE" MODIFY ("TITLE" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLETMODULE" MODIFY ("CONFIG" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLETMODULE" MODIFY ("PANECONFIG" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLETMODULE" MODIFY ("DASHLETCONFIG" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLETMODULE" MODIFY ("CREATEDBY" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHLETMODULE" MODIFY ("CREATED" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "ENTITYAUTH" ADD CONSTRAINT "ENTITYAUTH_PK" PRIMARY KEY ("ID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS"  ENABLE;
   --end line--
   ALTER TABLE  "ENTITYAUTH" MODIFY ("ID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "ENTITYAUTH" MODIFY ("ENTITYTYPE" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "ENTITYAUTH" MODIFY ("ENTITYID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "ENTITYAUTH" MODIFY ("ROLEORUSER" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "ENTITYAUTH" MODIFY ("PERMISSION" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "ENTITYAUTH" MODIFY ("AUTHTYPE" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHBOARD" ADD CONSTRAINT "DASHBOARD_PK" PRIMARY KEY ("ID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS"  ENABLE;
   --end line--
   ALTER TABLE  "DASHBOARD" MODIFY ("ID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHBOARD" MODIFY ("LAYOUT" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHBOARD" MODIFY ("CREATEDBY" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "DASHBOARD" MODIFY ("CREATED" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "TAGRELATION" MODIFY ("ID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "TAGRELATION" MODIFY ("TAGID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "TAGRELATION" MODIFY ("CONTROLID" NOT NULL ENABLE);
   --end line--
   ALTER TABLE  "TAGRELATION" MODIFY ("CONTROLLER" NOT NULL ENABLE);
      --end line--
   ALTER TABLE  "TAGRELATION" ADD CONSTRAINT "TAGRELATION_PK" PRIMARY KEY ("ID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "USERS"  ENABLE;
     --end line--
    ALTER TABLE "DASHLET" ADD CONSTRAINT "DASHLET_DASHBOARD_FK1" FOREIGN KEY ("DASHBOARDID")
	  REFERENCES "DASHBOARD" ("ID") ON DELETE CASCADE ENABLE;
 --end line--
  ALTER TABLE "DASHLET" ADD CONSTRAINT "DASHLET_DASHLETMODULE_FK1" FOREIGN KEY ("DASHLETMODULEID")
	  REFERENCES "DASHLETMODULE" ("ID") ON DELETE CASCADE ENABLE;
    --end line--
    ALTER TABLE "TAGRELATION" ADD CONSTRAINT "TAGRELATION_TAG_FK1" FOREIGN KEY ("TAGID")
	  REFERENCES "TAG" ("ID") ON DELETE CASCADE ENABLE;
   --end line--   create or replace TRIGGER Dashboard_id_TRIG BEFORE INSERT OR UPDATE ON Dashboard  FOR EACH ROW  DECLARE   v_newVal NUMBER(12) := 0;  v_incval NUMBER(12) := 0;  BEGIN    IF INSERTING AND :new.id IS NULL THEN      SELECT  Dashboard_id_SEQ.NEXTVAL INTO v_newVal FROM DUAL;           IF v_newVal = 1 THEN               SELECT NVL(max(id),0) INTO v_newVal FROM Dashboard;        v_newVal := v_newVal + 1;              LOOP             EXIT WHEN v_incval>=v_newVal;             SELECT Dashboard_id_SEQ.nextval INTO v_incval FROM dual;        END LOOP;      END IF;     :new.id := v_newVal;    END IF;  END;  
   --end line--create or replace TRIGGER "DASHLET_ID_TRIG" BEFORE INSERT OR UPDATE ON Dashlet  FOR EACH ROW 
DECLARE   v_newVal NUMBER(12) := 0;  v_incval NUMBER(12) := 0;  
BEGIN    
IF INSERTING AND :new.id IS NULL THEN      
SELECT  Dashlet_id_SEQ.NEXTVAL INTO v_newVal FROM DUAL;      
IF v_newVal = 1 THEN         
SELECT NVL(max(id),0) INTO v_newVal FROM Dashlet;        v_newVal := v_newVal + 1;          
LOOP             EXIT WHEN v_incval>=v_newVal;            
SELECT Dashlet_id_SEQ.nextval INTO v_incval FROM dual;     
END LOOP;     
END IF;       
:new.id := v_newVal;    
END IF; 
END;
   --end line-- create or replace TRIGGER EntityAuth_id_TRIG BEFORE INSERT OR UPDATE ON EntityAuth
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.id IS NULL THEN
    SELECT  EntityAuth_id_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN 
      --get the max indentity value from the table
      SELECT NVL(max(id),0) INTO v_newVal FROM EntityAuth;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT EntityAuth_id_SEQ.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
   -- assign the value from the sequence to emulate the identity column
   :new.id := v_newVal;
  END IF;
END;
   --end line-- create or replace TRIGGER Tag_id_TRIG BEFORE INSERT OR UPDATE ON Tag
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.id IS NULL THEN
    SELECT  Tag_id_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN 
      --get the max indentity value from the table
      SELECT NVL(max(id),0) INTO v_newVal FROM Tag;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT Tag_id_SEQ.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
   -- assign the value from the sequence to emulate the identity column
   :new.id := v_newVal;
  END IF;
END;
   --end line--  create or replace TRIGGER TagRelation_id_TRIG BEFORE INSERT OR UPDATE ON TagRelation
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.id IS NULL THEN
    SELECT  TagRelation_id_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN 
      --get the max indentity value from the table
      SELECT NVL(max(id),0) INTO v_newVal FROM TagRelation;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT TagRelation_id_SEQ.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
   -- assign the value from the sequence to emulate the identity column
   :new.id := v_newVal;
  END IF;
END;
   --end line--  create or replace TRIGGER DashletModule_id_TRIG BEFORE INSERT OR UPDATE ON DashletModule
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.id IS NULL THEN
    SELECT  DashletModule_id_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN 
      --get the max indentity value from the table
      SELECT NVL(max(id),0) INTO v_newVal FROM DashletModule;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT DashletModule_id_SEQ.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
   -- assign the value from the sequence to emulate the identity column
   :new.id := v_newVal;
  END IF;
END;