//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "DASHLET_DASHBOARD_FK1", "DASHBOARD", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.Dashboard), "DASHLET", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.Dashlet), true)]
[assembly: EdmRelationshipAttribute("Model", "DASHLET_DASHLETMODULE_FK1", "DASHLETMODULE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.DashletModule), "DASHLET", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.Dashlet), true)]
[assembly: EdmRelationshipAttribute("Model", "TAGRELATION_TAG_FK1", "TAG", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.Tag), "TAGRELATION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.TagRelation), true)]
[assembly: EdmRelationshipAttribute("Model", "DASHBOARDTAGRELATION", "DASHBOARD", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.Dashboard), "TAGRELATION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.TagRelation), true)]
[assembly: EdmRelationshipAttribute("Model", "DASHLETTAGRELATION", "DASHLET", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.Dashlet), "TAGRELATION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.TagRelation), true)]
[assembly: EdmRelationshipAttribute("Model", "DASHLETMODULETAGRELATION", "DASHLETMODULE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.DashletModule), "TAGRELATION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.TagRelation), true)]

#endregion

namespace JDash.OracleProvider.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OracleDashboardEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OracleDashboardEntities object using the connection string found in the 'OracleDashboardEntities' section of the application configuration file.
        /// </summary>
        public OracleDashboardEntities() : base("name=OracleDashboardEntities", "OracleDashboardEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OracleDashboardEntities object.
        /// </summary>
        public OracleDashboardEntities(string connectionString) : base(connectionString, "OracleDashboardEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OracleDashboardEntities object.
        /// </summary>
        public OracleDashboardEntities(EntityConnection connection) : base(connection, "OracleDashboardEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dashboard> DASHBOARD
        {
            get
            {
                if ((_DASHBOARD == null))
                {
                    _DASHBOARD = base.CreateObjectSet<Dashboard>("DASHBOARD");
                }
                return _DASHBOARD;
            }
        }
        private ObjectSet<Dashboard> _DASHBOARD;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dashlet> DASHLET
        {
            get
            {
                if ((_DASHLET == null))
                {
                    _DASHLET = base.CreateObjectSet<Dashlet>("DASHLET");
                }
                return _DASHLET;
            }
        }
        private ObjectSet<Dashlet> _DASHLET;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DashletModule> DASHLETMODULE
        {
            get
            {
                if ((_DASHLETMODULE == null))
                {
                    _DASHLETMODULE = base.CreateObjectSet<DashletModule>("DASHLETMODULE");
                }
                return _DASHLETMODULE;
            }
        }
        private ObjectSet<DashletModule> _DASHLETMODULE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> TAG
        {
            get
            {
                if ((_TAG == null))
                {
                    _TAG = base.CreateObjectSet<Tag>("TAG");
                }
                return _TAG;
            }
        }
        private ObjectSet<Tag> _TAG;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TagRelation> TAGRELATION
        {
            get
            {
                if ((_TAGRELATION == null))
                {
                    _TAGRELATION = base.CreateObjectSet<TagRelation>("TAGRELATION");
                }
                return _TAGRELATION;
            }
        }
        private ObjectSet<TagRelation> _TAGRELATION;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DASHBOARD EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDASHBOARD(Dashboard dashboard)
        {
            base.AddObject("DASHBOARD", dashboard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DASHLET EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDASHLET(Dashlet dashlet)
        {
            base.AddObject("DASHLET", dashlet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DASHLETMODULE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDASHLETMODULE(DashletModule dashletModule)
        {
            base.AddObject("DASHLETMODULE", dashletModule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TAG EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTAG(Tag tag)
        {
            base.AddObject("TAG", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TAGRELATION EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTAGRELATION(TagRelation tagRelation)
        {
            base.AddObject("TAGRELATION", tagRelation);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Dashboard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dashboard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dashboard object.
        /// </summary>
        /// <param name="dASHBOARDID">Initial value of the DASHBOARDID property.</param>
        /// <param name="lAYOUT">Initial value of the LAYOUT property.</param>
        /// <param name="sHARETYPE">Initial value of the SHARETYPE property.</param>
        /// <param name="cREATEDBY">Initial value of the CREATEDBY property.</param>
        /// <param name="cREATED">Initial value of the CREATED property.</param>
        public static Dashboard CreateDashboard(global::System.Int32 dASHBOARDID, global::System.String lAYOUT, global::System.String sHARETYPE, global::System.String cREATEDBY, global::System.DateTime cREATED)
        {
            Dashboard dashboard = new Dashboard();
            dashboard.DASHBOARDID = dASHBOARDID;
            dashboard.LAYOUT = lAYOUT;
            dashboard.SHARETYPE = sHARETYPE;
            dashboard.CREATEDBY = cREATEDBY;
            dashboard.CREATED = cREATED;
            return dashboard;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DASHBOARDID
        {
            get
            {
                return _DASHBOARDID;
            }
            set
            {
                if (_DASHBOARDID != value)
                {
                    OnDASHBOARDIDChanging(value);
                    ReportPropertyChanging("DASHBOARDID");
                    _DASHBOARDID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DASHBOARDID");
                    OnDASHBOARDIDChanged();
                }
            }
        }
        private global::System.Int32 _DASHBOARDID;
        partial void OnDASHBOARDIDChanging(global::System.Int32 value);
        partial void OnDASHBOARDIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LAYOUT
        {
            get
            {
                return _LAYOUT;
            }
            set
            {
                OnLAYOUTChanging(value);
                ReportPropertyChanging("LAYOUT");
                _LAYOUT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LAYOUT");
                OnLAYOUTChanged();
            }
        }
        private global::System.String _LAYOUT;
        partial void OnLAYOUTChanging(global::System.String value);
        partial void OnLAYOUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONFIG
        {
            get
            {
                return _CONFIG;
            }
            set
            {
                OnCONFIGChanging(value);
                ReportPropertyChanging("CONFIG");
                _CONFIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONFIG");
                OnCONFIGChanged();
            }
        }
        private global::System.String _CONFIG;
        partial void OnCONFIGChanging(global::System.String value);
        partial void OnCONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PANECONFIG
        {
            get
            {
                return _PANECONFIG;
            }
            set
            {
                OnPANECONFIGChanging(value);
                ReportPropertyChanging("PANECONFIG");
                _PANECONFIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PANECONFIG");
                OnPANECONFIGChanged();
            }
        }
        private global::System.String _PANECONFIG;
        partial void OnPANECONFIGChanging(global::System.String value);
        partial void OnPANECONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AUTHORIZATION
        {
            get
            {
                return _AUTHORIZATION;
            }
            set
            {
                OnAUTHORIZATIONChanging(value);
                ReportPropertyChanging("AUTHORIZATION");
                _AUTHORIZATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AUTHORIZATION");
                OnAUTHORIZATIONChanged();
            }
        }
        private global::System.String _AUTHORIZATION;
        partial void OnAUTHORIZATIONChanging(global::System.String value);
        partial void OnAUTHORIZATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SHARETYPE
        {
            get
            {
                return _SHARETYPE;
            }
            set
            {
                OnSHARETYPEChanging(value);
                ReportPropertyChanging("SHARETYPE");
                _SHARETYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SHARETYPE");
                OnSHARETYPEChanged();
            }
        }
        private global::System.String _SHARETYPE;
        partial void OnSHARETYPEChanging(global::System.String value);
        partial void OnSHARETYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STYLE
        {
            get
            {
                return _STYLE;
            }
            set
            {
                OnSTYLEChanging(value);
                ReportPropertyChanging("STYLE");
                _STYLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STYLE");
                OnSTYLEChanged();
            }
        }
        private global::System.String _STYLE;
        partial void OnSTYLEChanging(global::System.String value);
        partial void OnSTYLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLS
        {
            get
            {
                return _CLS;
            }
            set
            {
                OnCLSChanging(value);
                ReportPropertyChanging("CLS");
                _CLS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLS");
                OnCLSChanged();
            }
        }
        private global::System.String _CLS;
        partial void OnCLSChanging(global::System.String value);
        partial void OnCLSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTR
        {
            get
            {
                return _ATTR;
            }
            set
            {
                OnATTRChanging(value);
                ReportPropertyChanging("ATTR");
                _ATTR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTR");
                OnATTRChanged();
            }
        }
        private global::System.String _ATTR;
        partial void OnATTRChanging(global::System.String value);
        partial void OnATTRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUPNAME
        {
            get
            {
                return _GROUPNAME;
            }
            set
            {
                OnGROUPNAMEChanging(value);
                ReportPropertyChanging("GROUPNAME");
                _GROUPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUPNAME");
                OnGROUPNAMEChanged();
            }
        }
        private global::System.String _GROUPNAME;
        partial void OnGROUPNAMEChanging(global::System.String value);
        partial void OnGROUPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEDBY
        {
            get
            {
                return _CREATEDBY;
            }
            set
            {
                OnCREATEDBYChanging(value);
                ReportPropertyChanging("CREATEDBY");
                _CREATEDBY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEDBY");
                OnCREATEDBYChanged();
            }
        }
        private global::System.String _CREATEDBY;
        partial void OnCREATEDBYChanging(global::System.String value);
        partial void OnCREATEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODIFIEDBY
        {
            get
            {
                return _MODIFIEDBY;
            }
            set
            {
                OnMODIFIEDBYChanging(value);
                ReportPropertyChanging("MODIFIEDBY");
                _MODIFIEDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODIFIEDBY");
                OnMODIFIEDBYChanged();
            }
        }
        private global::System.String _MODIFIEDBY;
        partial void OnMODIFIEDBYChanging(global::System.String value);
        partial void OnMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHAREDBY
        {
            get
            {
                return _SHAREDBY;
            }
            set
            {
                OnSHAREDBYChanging(value);
                ReportPropertyChanging("SHAREDBY");
                _SHAREDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHAREDBY");
                OnSHAREDBYChanged();
            }
        }
        private global::System.String _SHAREDBY;
        partial void OnSHAREDBYChanging(global::System.String value);
        partial void OnSHAREDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED
        {
            get
            {
                return _CREATED;
            }
            set
            {
                OnCREATEDChanging(value);
                ReportPropertyChanging("CREATED");
                _CREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED");
                OnCREATEDChanged();
            }
        }
        private global::System.DateTime _CREATED;
        partial void OnCREATEDChanging(global::System.DateTime value);
        partial void OnCREATEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MODIFIED
        {
            get
            {
                return _MODIFIED;
            }
            set
            {
                OnMODIFIEDChanging(value);
                ReportPropertyChanging("MODIFIED");
                _MODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MODIFIED");
                OnMODIFIEDChanged();
            }
        }
        private Nullable<global::System.DateTime> _MODIFIED;
        partial void OnMODIFIEDChanging(Nullable<global::System.DateTime> value);
        partial void OnMODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SHARED
        {
            get
            {
                return _SHARED;
            }
            set
            {
                OnSHAREDChanging(value);
                ReportPropertyChanging("SHARED");
                _SHARED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHARED");
                OnSHAREDChanged();
            }
        }
        private Nullable<global::System.DateTime> _SHARED;
        partial void OnSHAREDChanging(Nullable<global::System.DateTime> value);
        partial void OnSHAREDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERDATA
        {
            get
            {
                return _USERDATA;
            }
            set
            {
                OnUSERDATAChanging(value);
                ReportPropertyChanging("USERDATA");
                _USERDATA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERDATA");
                OnUSERDATAChanged();
            }
        }
        private global::System.String _USERDATA;
        partial void OnUSERDATAChanging(global::System.String value);
        partial void OnUSERDATAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VIEWORDER
        {
            get
            {
                return _VIEWORDER;
            }
            set
            {
                OnVIEWORDERChanging(value);
                ReportPropertyChanging("VIEWORDER");
                _VIEWORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VIEWORDER");
                OnVIEWORDERChanged();
            }
        }
        private Nullable<global::System.Int32> _VIEWORDER;
        partial void OnVIEWORDERChanging(Nullable<global::System.Int32> value);
        partial void OnVIEWORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GROUPORDER
        {
            get
            {
                return _GROUPORDER;
            }
            set
            {
                OnGROUPORDERChanging(value);
                ReportPropertyChanging("GROUPORDER");
                _GROUPORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUPORDER");
                OnGROUPORDERChanged();
            }
        }
        private Nullable<global::System.Int32> _GROUPORDER;
        partial void OnGROUPORDERChanging(Nullable<global::System.Int32> value);
        partial void OnGROUPORDERChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLET_DASHBOARD_FK1", "DASHLET")]
        public EntityCollection<Dashlet> DASHLET
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dashlet>("Model.DASHLET_DASHBOARD_FK1", "DASHLET");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dashlet>("Model.DASHLET_DASHBOARD_FK1", "DASHLET", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHBOARDTAGRELATION", "TAGRELATION")]
        public EntityCollection<TagRelation> TAGRELATION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagRelation>("Model.DASHBOARDTAGRELATION", "TAGRELATION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagRelation>("Model.DASHBOARDTAGRELATION", "TAGRELATION", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Dashlet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dashlet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dashlet object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="dASHBOARDID">Initial value of the DASHBOARDID property.</param>
        /// <param name="dASHLETMODULEID">Initial value of the DASHLETMODULEID property.</param>
        /// <param name="pOSITION">Initial value of the POSITION property.</param>
        /// <param name="sHARTYPE">Initial value of the SHARTYPE property.</param>
        /// <param name="cREATEDBY">Initial value of the CREATEDBY property.</param>
        /// <param name="cREATED">Initial value of the CREATED property.</param>
        public static Dashlet CreateDashlet(global::System.Int32 id, global::System.Int32 dASHBOARDID, global::System.Int32 dASHLETMODULEID, global::System.String pOSITION, global::System.String sHARTYPE, global::System.String cREATEDBY, global::System.DateTime cREATED)
        {
            Dashlet dashlet = new Dashlet();
            dashlet.ID = id;
            dashlet.DASHBOARDID = dASHBOARDID;
            dashlet.DASHLETMODULEID = dASHLETMODULEID;
            dashlet.POSITION = pOSITION;
            dashlet.SHARTYPE = sHARTYPE;
            dashlet.CREATEDBY = cREATEDBY;
            dashlet.CREATED = cREATED;
            return dashlet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DASHBOARDID
        {
            get
            {
                return _DASHBOARDID;
            }
            set
            {
                OnDASHBOARDIDChanging(value);
                ReportPropertyChanging("DASHBOARDID");
                _DASHBOARDID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DASHBOARDID");
                OnDASHBOARDIDChanged();
            }
        }
        private global::System.Int32 _DASHBOARDID;
        partial void OnDASHBOARDIDChanging(global::System.Int32 value);
        partial void OnDASHBOARDIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DASHLETMODULEID
        {
            get
            {
                return _DASHLETMODULEID;
            }
            set
            {
                OnDASHLETMODULEIDChanging(value);
                ReportPropertyChanging("DASHLETMODULEID");
                _DASHLETMODULEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DASHLETMODULEID");
                OnDASHLETMODULEIDChanged();
            }
        }
        private global::System.Int32 _DASHLETMODULEID;
        partial void OnDASHLETMODULEIDChanging(global::System.Int32 value);
        partial void OnDASHLETMODULEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONFIG
        {
            get
            {
                return _CONFIG;
            }
            set
            {
                OnCONFIGChanging(value);
                ReportPropertyChanging("CONFIG");
                _CONFIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONFIG");
                OnCONFIGChanged();
            }
        }
        private global::System.String _CONFIG;
        partial void OnCONFIGChanging(global::System.String value);
        partial void OnCONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PANECONFIG
        {
            get
            {
                return _PANECONFIG;
            }
            set
            {
                OnPANECONFIGChanging(value);
                ReportPropertyChanging("PANECONFIG");
                _PANECONFIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PANECONFIG");
                OnPANECONFIGChanged();
            }
        }
        private global::System.String _PANECONFIG;
        partial void OnPANECONFIGChanging(global::System.String value);
        partial void OnPANECONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String POSITION
        {
            get
            {
                return _POSITION;
            }
            set
            {
                OnPOSITIONChanging(value);
                ReportPropertyChanging("POSITION");
                _POSITION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("POSITION");
                OnPOSITIONChanged();
            }
        }
        private global::System.String _POSITION;
        partial void OnPOSITIONChanging(global::System.String value);
        partial void OnPOSITIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AUTHORIZATION
        {
            get
            {
                return _AUTHORIZATION;
            }
            set
            {
                OnAUTHORIZATIONChanging(value);
                ReportPropertyChanging("AUTHORIZATION");
                _AUTHORIZATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AUTHORIZATION");
                OnAUTHORIZATIONChanged();
            }
        }
        private global::System.String _AUTHORIZATION;
        partial void OnAUTHORIZATIONChanging(global::System.String value);
        partial void OnAUTHORIZATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SHARTYPE
        {
            get
            {
                return _SHARTYPE;
            }
            set
            {
                OnSHARTYPEChanging(value);
                ReportPropertyChanging("SHARTYPE");
                _SHARTYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SHARTYPE");
                OnSHARTYPEChanged();
            }
        }
        private global::System.String _SHARTYPE;
        partial void OnSHARTYPEChanging(global::System.String value);
        partial void OnSHARTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STYLE
        {
            get
            {
                return _STYLE;
            }
            set
            {
                OnSTYLEChanging(value);
                ReportPropertyChanging("STYLE");
                _STYLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STYLE");
                OnSTYLEChanged();
            }
        }
        private global::System.String _STYLE;
        partial void OnSTYLEChanging(global::System.String value);
        partial void OnSTYLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLS
        {
            get
            {
                return _CLS;
            }
            set
            {
                OnCLSChanging(value);
                ReportPropertyChanging("CLS");
                _CLS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLS");
                OnCLSChanged();
            }
        }
        private global::System.String _CLS;
        partial void OnCLSChanging(global::System.String value);
        partial void OnCLSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTR
        {
            get
            {
                return _ATTR;
            }
            set
            {
                OnATTRChanging(value);
                ReportPropertyChanging("ATTR");
                _ATTR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTR");
                OnATTRChanged();
            }
        }
        private global::System.String _ATTR;
        partial void OnATTRChanging(global::System.String value);
        partial void OnATTRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUPNAME
        {
            get
            {
                return _GROUPNAME;
            }
            set
            {
                OnGROUPNAMEChanging(value);
                ReportPropertyChanging("GROUPNAME");
                _GROUPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUPNAME");
                OnGROUPNAMEChanged();
            }
        }
        private global::System.String _GROUPNAME;
        partial void OnGROUPNAMEChanging(global::System.String value);
        partial void OnGROUPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEDBY
        {
            get
            {
                return _CREATEDBY;
            }
            set
            {
                OnCREATEDBYChanging(value);
                ReportPropertyChanging("CREATEDBY");
                _CREATEDBY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEDBY");
                OnCREATEDBYChanged();
            }
        }
        private global::System.String _CREATEDBY;
        partial void OnCREATEDBYChanging(global::System.String value);
        partial void OnCREATEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODIFIEDBY
        {
            get
            {
                return _MODIFIEDBY;
            }
            set
            {
                OnMODIFIEDBYChanging(value);
                ReportPropertyChanging("MODIFIEDBY");
                _MODIFIEDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODIFIEDBY");
                OnMODIFIEDBYChanged();
            }
        }
        private global::System.String _MODIFIEDBY;
        partial void OnMODIFIEDBYChanging(global::System.String value);
        partial void OnMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHAREDBY
        {
            get
            {
                return _SHAREDBY;
            }
            set
            {
                OnSHAREDBYChanging(value);
                ReportPropertyChanging("SHAREDBY");
                _SHAREDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHAREDBY");
                OnSHAREDBYChanged();
            }
        }
        private global::System.String _SHAREDBY;
        partial void OnSHAREDBYChanging(global::System.String value);
        partial void OnSHAREDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED
        {
            get
            {
                return _CREATED;
            }
            set
            {
                OnCREATEDChanging(value);
                ReportPropertyChanging("CREATED");
                _CREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED");
                OnCREATEDChanged();
            }
        }
        private global::System.DateTime _CREATED;
        partial void OnCREATEDChanging(global::System.DateTime value);
        partial void OnCREATEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MODIFIED
        {
            get
            {
                return _MODIFIED;
            }
            set
            {
                OnMODIFIEDChanging(value);
                ReportPropertyChanging("MODIFIED");
                _MODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MODIFIED");
                OnMODIFIEDChanged();
            }
        }
        private Nullable<global::System.DateTime> _MODIFIED;
        partial void OnMODIFIEDChanging(Nullable<global::System.DateTime> value);
        partial void OnMODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SHARED
        {
            get
            {
                return _SHARED;
            }
            set
            {
                OnSHAREDChanging(value);
                ReportPropertyChanging("SHARED");
                _SHARED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHARED");
                OnSHAREDChanged();
            }
        }
        private Nullable<global::System.DateTime> _SHARED;
        partial void OnSHAREDChanging(Nullable<global::System.DateTime> value);
        partial void OnSHAREDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERDATA
        {
            get
            {
                return _USERDATA;
            }
            set
            {
                OnUSERDATAChanging(value);
                ReportPropertyChanging("USERDATA");
                _USERDATA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERDATA");
                OnUSERDATAChanged();
            }
        }
        private global::System.String _USERDATA;
        partial void OnUSERDATAChanging(global::System.String value);
        partial void OnUSERDATAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLET_DASHBOARD_FK1", "DASHBOARD")]
        public Dashboard DASHBOARD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("Model.DASHLET_DASHBOARD_FK1", "DASHBOARD").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("Model.DASHLET_DASHBOARD_FK1", "DASHBOARD").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dashboard> DASHBOARDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("Model.DASHLET_DASHBOARD_FK1", "DASHBOARD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dashboard>("Model.DASHLET_DASHBOARD_FK1", "DASHBOARD", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLET_DASHLETMODULE_FK1", "DASHLETMODULE")]
        public DashletModule DASHLETMODULE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("Model.DASHLET_DASHLETMODULE_FK1", "DASHLETMODULE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("Model.DASHLET_DASHLETMODULE_FK1", "DASHLETMODULE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DashletModule> DASHLETMODULEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("Model.DASHLET_DASHLETMODULE_FK1", "DASHLETMODULE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DashletModule>("Model.DASHLET_DASHLETMODULE_FK1", "DASHLETMODULE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLETTAGRELATION", "TAGRELATION")]
        public EntityCollection<TagRelation> TAGRELATION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagRelation>("Model.DASHLETTAGRELATION", "TAGRELATION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagRelation>("Model.DASHLETTAGRELATION", "TAGRELATION", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="DashletModule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DashletModule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DashletModule object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="pATH">Initial value of the PATH property.</param>
        /// <param name="tITLE">Initial value of the TITLE property.</param>
        /// <param name="cONFIG">Initial value of the CONFIG property.</param>
        /// <param name="pANECONFIG">Initial value of the PANECONFIG property.</param>
        /// <param name="dASHLETCONFIG">Initial value of the DASHLETCONFIG property.</param>
        /// <param name="sHARETYPE">Initial value of the SHARETYPE property.</param>
        /// <param name="cREATEDBY">Initial value of the CREATEDBY property.</param>
        /// <param name="cREATED">Initial value of the CREATED property.</param>
        public static DashletModule CreateDashletModule(global::System.Int32 id, global::System.String pATH, global::System.String tITLE, global::System.String cONFIG, global::System.String pANECONFIG, global::System.String dASHLETCONFIG, global::System.String sHARETYPE, global::System.String cREATEDBY, global::System.DateTime cREATED)
        {
            DashletModule dashletModule = new DashletModule();
            dashletModule.ID = id;
            dashletModule.PATH = pATH;
            dashletModule.TITLE = tITLE;
            dashletModule.CONFIG = cONFIG;
            dashletModule.PANECONFIG = pANECONFIG;
            dashletModule.DASHLETCONFIG = dASHLETCONFIG;
            dashletModule.SHARETYPE = sHARETYPE;
            dashletModule.CREATEDBY = cREATEDBY;
            dashletModule.CREATED = cREATED;
            return dashletModule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PATH
        {
            get
            {
                return _PATH;
            }
            set
            {
                OnPATHChanging(value);
                ReportPropertyChanging("PATH");
                _PATH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PATH");
                OnPATHChanged();
            }
        }
        private global::System.String _PATH;
        partial void OnPATHChanging(global::System.String value);
        partial void OnPATHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONFIG
        {
            get
            {
                return _CONFIG;
            }
            set
            {
                OnCONFIGChanging(value);
                ReportPropertyChanging("CONFIG");
                _CONFIG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CONFIG");
                OnCONFIGChanged();
            }
        }
        private global::System.String _CONFIG;
        partial void OnCONFIGChanging(global::System.String value);
        partial void OnCONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PANECONFIG
        {
            get
            {
                return _PANECONFIG;
            }
            set
            {
                OnPANECONFIGChanging(value);
                ReportPropertyChanging("PANECONFIG");
                _PANECONFIG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PANECONFIG");
                OnPANECONFIGChanged();
            }
        }
        private global::System.String _PANECONFIG;
        partial void OnPANECONFIGChanging(global::System.String value);
        partial void OnPANECONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DASHLETCONFIG
        {
            get
            {
                return _DASHLETCONFIG;
            }
            set
            {
                OnDASHLETCONFIGChanging(value);
                ReportPropertyChanging("DASHLETCONFIG");
                _DASHLETCONFIG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DASHLETCONFIG");
                OnDASHLETCONFIGChanged();
            }
        }
        private global::System.String _DASHLETCONFIG;
        partial void OnDASHLETCONFIGChanging(global::System.String value);
        partial void OnDASHLETCONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AUTHORIZATION
        {
            get
            {
                return _AUTHORIZATION;
            }
            set
            {
                OnAUTHORIZATIONChanging(value);
                ReportPropertyChanging("AUTHORIZATION");
                _AUTHORIZATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AUTHORIZATION");
                OnAUTHORIZATIONChanged();
            }
        }
        private global::System.String _AUTHORIZATION;
        partial void OnAUTHORIZATIONChanging(global::System.String value);
        partial void OnAUTHORIZATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SHARETYPE
        {
            get
            {
                return _SHARETYPE;
            }
            set
            {
                OnSHARETYPEChanging(value);
                ReportPropertyChanging("SHARETYPE");
                _SHARETYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SHARETYPE");
                OnSHARETYPEChanged();
            }
        }
        private global::System.String _SHARETYPE;
        partial void OnSHARETYPEChanging(global::System.String value);
        partial void OnSHARETYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STYLE
        {
            get
            {
                return _STYLE;
            }
            set
            {
                OnSTYLEChanging(value);
                ReportPropertyChanging("STYLE");
                _STYLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STYLE");
                OnSTYLEChanged();
            }
        }
        private global::System.String _STYLE;
        partial void OnSTYLEChanging(global::System.String value);
        partial void OnSTYLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLS
        {
            get
            {
                return _CLS;
            }
            set
            {
                OnCLSChanging(value);
                ReportPropertyChanging("CLS");
                _CLS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLS");
                OnCLSChanged();
            }
        }
        private global::System.String _CLS;
        partial void OnCLSChanging(global::System.String value);
        partial void OnCLSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTR
        {
            get
            {
                return _ATTR;
            }
            set
            {
                OnATTRChanging(value);
                ReportPropertyChanging("ATTR");
                _ATTR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTR");
                OnATTRChanged();
            }
        }
        private global::System.String _ATTR;
        partial void OnATTRChanging(global::System.String value);
        partial void OnATTRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEDBY
        {
            get
            {
                return _CREATEDBY;
            }
            set
            {
                OnCREATEDBYChanging(value);
                ReportPropertyChanging("CREATEDBY");
                _CREATEDBY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEDBY");
                OnCREATEDBYChanged();
            }
        }
        private global::System.String _CREATEDBY;
        partial void OnCREATEDBYChanging(global::System.String value);
        partial void OnCREATEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODIFIEDBY
        {
            get
            {
                return _MODIFIEDBY;
            }
            set
            {
                OnMODIFIEDBYChanging(value);
                ReportPropertyChanging("MODIFIEDBY");
                _MODIFIEDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODIFIEDBY");
                OnMODIFIEDBYChanged();
            }
        }
        private global::System.String _MODIFIEDBY;
        partial void OnMODIFIEDBYChanging(global::System.String value);
        partial void OnMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHAREDBY
        {
            get
            {
                return _SHAREDBY;
            }
            set
            {
                OnSHAREDBYChanging(value);
                ReportPropertyChanging("SHAREDBY");
                _SHAREDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHAREDBY");
                OnSHAREDBYChanged();
            }
        }
        private global::System.String _SHAREDBY;
        partial void OnSHAREDBYChanging(global::System.String value);
        partial void OnSHAREDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED
        {
            get
            {
                return _CREATED;
            }
            set
            {
                OnCREATEDChanging(value);
                ReportPropertyChanging("CREATED");
                _CREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED");
                OnCREATEDChanged();
            }
        }
        private global::System.DateTime _CREATED;
        partial void OnCREATEDChanging(global::System.DateTime value);
        partial void OnCREATEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MODIFIED
        {
            get
            {
                return _MODIFIED;
            }
            set
            {
                OnMODIFIEDChanging(value);
                ReportPropertyChanging("MODIFIED");
                _MODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MODIFIED");
                OnMODIFIEDChanged();
            }
        }
        private Nullable<global::System.DateTime> _MODIFIED;
        partial void OnMODIFIEDChanging(Nullable<global::System.DateTime> value);
        partial void OnMODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SHARED
        {
            get
            {
                return _SHARED;
            }
            set
            {
                OnSHAREDChanging(value);
                ReportPropertyChanging("SHARED");
                _SHARED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHARED");
                OnSHAREDChanged();
            }
        }
        private Nullable<global::System.DateTime> _SHARED;
        partial void OnSHAREDChanging(Nullable<global::System.DateTime> value);
        partial void OnSHAREDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUPNAME
        {
            get
            {
                return _GROUPNAME;
            }
            set
            {
                OnGROUPNAMEChanging(value);
                ReportPropertyChanging("GROUPNAME");
                _GROUPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUPNAME");
                OnGROUPNAMEChanged();
            }
        }
        private global::System.String _GROUPNAME;
        partial void OnGROUPNAMEChanging(global::System.String value);
        partial void OnGROUPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERDATA
        {
            get
            {
                return _USERDATA;
            }
            set
            {
                OnUSERDATAChanging(value);
                ReportPropertyChanging("USERDATA");
                _USERDATA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERDATA");
                OnUSERDATAChanged();
            }
        }
        private global::System.String _USERDATA;
        partial void OnUSERDATAChanging(global::System.String value);
        partial void OnUSERDATAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VIEWORDER
        {
            get
            {
                return _VIEWORDER;
            }
            set
            {
                OnVIEWORDERChanging(value);
                ReportPropertyChanging("VIEWORDER");
                _VIEWORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VIEWORDER");
                OnVIEWORDERChanged();
            }
        }
        private Nullable<global::System.Int32> _VIEWORDER;
        partial void OnVIEWORDERChanging(Nullable<global::System.Int32> value);
        partial void OnVIEWORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GROUPORDER
        {
            get
            {
                return _GROUPORDER;
            }
            set
            {
                OnGROUPORDERChanging(value);
                ReportPropertyChanging("GROUPORDER");
                _GROUPORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUPORDER");
                OnGROUPORDERChanged();
            }
        }
        private Nullable<global::System.Int32> _GROUPORDER;
        partial void OnGROUPORDERChanging(Nullable<global::System.Int32> value);
        partial void OnGROUPORDERChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLET_DASHLETMODULE_FK1", "DASHLET")]
        public EntityCollection<Dashlet> DASHLET
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dashlet>("Model.DASHLET_DASHLETMODULE_FK1", "DASHLET");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dashlet>("Model.DASHLET_DASHLETMODULE_FK1", "DASHLET", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLETMODULETAGRELATION", "TAGRELATION")]
        public EntityCollection<TagRelation> TAGRELATION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagRelation>("Model.DASHLETMODULETAGRELATION", "TAGRELATION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagRelation>("Model.DASHLETMODULETAGRELATION", "TAGRELATION", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tAGID">Initial value of the TAGID property.</param>
        /// <param name="tAGNAME">Initial value of the TAGNAME property.</param>
        public static Tag CreateTag(global::System.Int32 tAGID, global::System.String tAGNAME)
        {
            Tag tag = new Tag();
            tag.TAGID = tAGID;
            tag.TAGNAME = tAGNAME;
            return tag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TAGID
        {
            get
            {
                return _TAGID;
            }
            set
            {
                if (_TAGID != value)
                {
                    OnTAGIDChanging(value);
                    ReportPropertyChanging("TAGID");
                    _TAGID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TAGID");
                    OnTAGIDChanged();
                }
            }
        }
        private global::System.Int32 _TAGID;
        partial void OnTAGIDChanging(global::System.Int32 value);
        partial void OnTAGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAGNAME
        {
            get
            {
                return _TAGNAME;
            }
            set
            {
                OnTAGNAMEChanging(value);
                ReportPropertyChanging("TAGNAME");
                _TAGNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TAGNAME");
                OnTAGNAMEChanged();
            }
        }
        private global::System.String _TAGNAME;
        partial void OnTAGNAMEChanging(global::System.String value);
        partial void OnTAGNAMEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "TAGRELATION_TAG_FK1", "TAGRELATION")]
        public EntityCollection<TagRelation> TAGRELATION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagRelation>("Model.TAGRELATION_TAG_FK1", "TAGRELATION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagRelation>("Model.TAGRELATION_TAG_FK1", "TAGRELATION", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TagRelation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TagRelation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TagRelation object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tAGID">Initial value of the TAGID property.</param>
        /// <param name="cONTROLID">Initial value of the CONTROLID property.</param>
        /// <param name="cONTROLLER">Initial value of the CONTROLLER property.</param>
        public static TagRelation CreateTagRelation(global::System.Int32 id, global::System.Int32 tAGID, global::System.Int32 cONTROLID, global::System.String cONTROLLER)
        {
            TagRelation tagRelation = new TagRelation();
            tagRelation.ID = id;
            tagRelation.TAGID = tAGID;
            tagRelation.CONTROLID = cONTROLID;
            tagRelation.CONTROLLER = cONTROLLER;
            return tagRelation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TAGID
        {
            get
            {
                return _TAGID;
            }
            set
            {
                OnTAGIDChanging(value);
                ReportPropertyChanging("TAGID");
                _TAGID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAGID");
                OnTAGIDChanged();
            }
        }
        private global::System.Int32 _TAGID;
        partial void OnTAGIDChanging(global::System.Int32 value);
        partial void OnTAGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CONTROLID
        {
            get
            {
                return _CONTROLID;
            }
            set
            {
                OnCONTROLIDChanging(value);
                ReportPropertyChanging("CONTROLID");
                _CONTROLID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CONTROLID");
                OnCONTROLIDChanged();
            }
        }
        private global::System.Int32 _CONTROLID;
        partial void OnCONTROLIDChanging(global::System.Int32 value);
        partial void OnCONTROLIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONTROLLER
        {
            get
            {
                return _CONTROLLER;
            }
            set
            {
                OnCONTROLLERChanging(value);
                ReportPropertyChanging("CONTROLLER");
                _CONTROLLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CONTROLLER");
                OnCONTROLLERChanged();
            }
        }
        private global::System.String _CONTROLLER;
        partial void OnCONTROLLERChanging(global::System.String value);
        partial void OnCONTROLLERChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "TAGRELATION_TAG_FK1", "TAG")]
        public Tag TAG
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("Model.TAGRELATION_TAG_FK1", "TAG").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("Model.TAGRELATION_TAG_FK1", "TAG").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tag> TAGReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("Model.TAGRELATION_TAG_FK1", "TAG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tag>("Model.TAGRELATION_TAG_FK1", "TAG", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHBOARDTAGRELATION", "DASHBOARD")]
        public Dashboard DASHBOARD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("Model.DASHBOARDTAGRELATION", "DASHBOARD").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("Model.DASHBOARDTAGRELATION", "DASHBOARD").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dashboard> DASHBOARDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashboard>("Model.DASHBOARDTAGRELATION", "DASHBOARD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dashboard>("Model.DASHBOARDTAGRELATION", "DASHBOARD", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLETTAGRELATION", "DASHLET")]
        public Dashlet DASHLET
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashlet>("Model.DASHLETTAGRELATION", "DASHLET").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashlet>("Model.DASHLETTAGRELATION", "DASHLET").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dashlet> DASHLETReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dashlet>("Model.DASHLETTAGRELATION", "DASHLET");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dashlet>("Model.DASHLETTAGRELATION", "DASHLET", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLETMODULETAGRELATION", "DASHLETMODULE")]
        public DashletModule DASHLETMODULE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("Model.DASHLETMODULETAGRELATION", "DASHLETMODULE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("Model.DASHLETMODULETAGRELATION", "DASHLETMODULE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DashletModule> DASHLETMODULEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DashletModule>("Model.DASHLETMODULETAGRELATION", "DASHLETMODULE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DashletModule>("Model.DASHLETMODULETAGRELATION", "DASHLETMODULE", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
