//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "DASHBOARDDASHLET", "DASHBOARD", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.DASHBOARD), "DASHLET", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.DASHLET), true)]
[assembly: EdmRelationshipAttribute("Model", "DASHLETMODULEDASHLET", "DASHLETMODULE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.DASHLETMODULE), "DASHLET", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.DASHLET), true)]
[assembly: EdmRelationshipAttribute("Model", "TAGTAGRELATION", "TAG", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JDash.OracleProvider.Models.TAG), "TAGRELATION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JDash.OracleProvider.Models.TAGRELATION), true)]

#endregion

namespace JDash.OracleProvider.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DASHBOARD> DASHBOARD
        {
            get
            {
                if ((_DASHBOARD == null))
                {
                    _DASHBOARD = base.CreateObjectSet<DASHBOARD>("DASHBOARD");
                }
                return _DASHBOARD;
            }
        }
        private ObjectSet<DASHBOARD> _DASHBOARD;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DASHLET> DASHLET
        {
            get
            {
                if ((_DASHLET == null))
                {
                    _DASHLET = base.CreateObjectSet<DASHLET>("DASHLET");
                }
                return _DASHLET;
            }
        }
        private ObjectSet<DASHLET> _DASHLET;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DASHLETMODULE> DASHLETMODULE
        {
            get
            {
                if ((_DASHLETMODULE == null))
                {
                    _DASHLETMODULE = base.CreateObjectSet<DASHLETMODULE>("DASHLETMODULE");
                }
                return _DASHLETMODULE;
            }
        }
        private ObjectSet<DASHLETMODULE> _DASHLETMODULE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ENTITYAUTH> ENTITYAUTH
        {
            get
            {
                if ((_ENTITYAUTH == null))
                {
                    _ENTITYAUTH = base.CreateObjectSet<ENTITYAUTH>("ENTITYAUTH");
                }
                return _ENTITYAUTH;
            }
        }
        private ObjectSet<ENTITYAUTH> _ENTITYAUTH;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TAG> TAG
        {
            get
            {
                if ((_TAG == null))
                {
                    _TAG = base.CreateObjectSet<TAG>("TAG");
                }
                return _TAG;
            }
        }
        private ObjectSet<TAG> _TAG;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TAGRELATION> TAGRELATION
        {
            get
            {
                if ((_TAGRELATION == null))
                {
                    _TAGRELATION = base.CreateObjectSet<TAGRELATION>("TAGRELATION");
                }
                return _TAGRELATION;
            }
        }
        private ObjectSet<TAGRELATION> _TAGRELATION;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DASHBOARD EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDASHBOARD(DASHBOARD dASHBOARD)
        {
            base.AddObject("DASHBOARD", dASHBOARD);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DASHLET EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDASHLET(DASHLET dASHLET)
        {
            base.AddObject("DASHLET", dASHLET);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DASHLETMODULE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDASHLETMODULE(DASHLETMODULE dASHLETMODULE)
        {
            base.AddObject("DASHLETMODULE", dASHLETMODULE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ENTITYAUTH EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToENTITYAUTH(ENTITYAUTH eNTITYAUTH)
        {
            base.AddObject("ENTITYAUTH", eNTITYAUTH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TAG EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTAG(TAG tAG)
        {
            base.AddObject("TAG", tAG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TAGRELATION EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTAGRELATION(TAGRELATION tAGRELATION)
        {
            base.AddObject("TAGRELATION", tAGRELATION);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="DASHBOARD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DASHBOARD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DASHBOARD object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="lAYOUT">Initial value of the LAYOUT property.</param>
        /// <param name="cREATEDBY">Initial value of the CREATEDBY property.</param>
        /// <param name="cREATED">Initial value of the CREATED property.</param>
        public static DASHBOARD CreateDASHBOARD(global::System.Int32 id, global::System.String lAYOUT, global::System.String cREATEDBY, global::System.DateTime cREATED)
        {
            DASHBOARD dASHBOARD = new DASHBOARD();
            dASHBOARD.ID = id;
            dASHBOARD.LAYOUT = lAYOUT;
            dASHBOARD.CREATEDBY = cREATEDBY;
            dASHBOARD.CREATED = cREATED;
            return dASHBOARD;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LAYOUT
        {
            get
            {
                return _LAYOUT;
            }
            set
            {
                OnLAYOUTChanging(value);
                ReportPropertyChanging("LAYOUT");
                _LAYOUT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LAYOUT");
                OnLAYOUTChanged();
            }
        }
        private global::System.String _LAYOUT;
        partial void OnLAYOUTChanging(global::System.String value);
        partial void OnLAYOUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONFIG
        {
            get
            {
                return _CONFIG;
            }
            set
            {
                OnCONFIGChanging(value);
                ReportPropertyChanging("CONFIG");
                _CONFIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONFIG");
                OnCONFIGChanged();
            }
        }
        private global::System.String _CONFIG;
        partial void OnCONFIGChanging(global::System.String value);
        partial void OnCONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PANECONFIG
        {
            get
            {
                return _PANECONFIG;
            }
            set
            {
                OnPANECONFIGChanging(value);
                ReportPropertyChanging("PANECONFIG");
                _PANECONFIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PANECONFIG");
                OnPANECONFIGChanged();
            }
        }
        private global::System.String _PANECONFIG;
        partial void OnPANECONFIGChanging(global::System.String value);
        partial void OnPANECONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STYLE
        {
            get
            {
                return _STYLE;
            }
            set
            {
                OnSTYLEChanging(value);
                ReportPropertyChanging("STYLE");
                _STYLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STYLE");
                OnSTYLEChanged();
            }
        }
        private global::System.String _STYLE;
        partial void OnSTYLEChanging(global::System.String value);
        partial void OnSTYLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLS
        {
            get
            {
                return _CLS;
            }
            set
            {
                OnCLSChanging(value);
                ReportPropertyChanging("CLS");
                _CLS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLS");
                OnCLSChanged();
            }
        }
        private global::System.String _CLS;
        partial void OnCLSChanging(global::System.String value);
        partial void OnCLSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTR
        {
            get
            {
                return _ATTR;
            }
            set
            {
                OnATTRChanging(value);
                ReportPropertyChanging("ATTR");
                _ATTR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTR");
                OnATTRChanged();
            }
        }
        private global::System.String _ATTR;
        partial void OnATTRChanging(global::System.String value);
        partial void OnATTRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUPNAME
        {
            get
            {
                return _GROUPNAME;
            }
            set
            {
                OnGROUPNAMEChanging(value);
                ReportPropertyChanging("GROUPNAME");
                _GROUPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUPNAME");
                OnGROUPNAMEChanged();
            }
        }
        private global::System.String _GROUPNAME;
        partial void OnGROUPNAMEChanging(global::System.String value);
        partial void OnGROUPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEDBY
        {
            get
            {
                return _CREATEDBY;
            }
            set
            {
                OnCREATEDBYChanging(value);
                ReportPropertyChanging("CREATEDBY");
                _CREATEDBY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEDBY");
                OnCREATEDBYChanged();
            }
        }
        private global::System.String _CREATEDBY;
        partial void OnCREATEDBYChanging(global::System.String value);
        partial void OnCREATEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODIFIEDBY
        {
            get
            {
                return _MODIFIEDBY;
            }
            set
            {
                OnMODIFIEDBYChanging(value);
                ReportPropertyChanging("MODIFIEDBY");
                _MODIFIEDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODIFIEDBY");
                OnMODIFIEDBYChanged();
            }
        }
        private global::System.String _MODIFIEDBY;
        partial void OnMODIFIEDBYChanging(global::System.String value);
        partial void OnMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHAREDBY
        {
            get
            {
                return _SHAREDBY;
            }
            set
            {
                OnSHAREDBYChanging(value);
                ReportPropertyChanging("SHAREDBY");
                _SHAREDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHAREDBY");
                OnSHAREDBYChanged();
            }
        }
        private global::System.String _SHAREDBY;
        partial void OnSHAREDBYChanging(global::System.String value);
        partial void OnSHAREDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED
        {
            get
            {
                return _CREATED;
            }
            set
            {
                OnCREATEDChanging(value);
                ReportPropertyChanging("CREATED");
                _CREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED");
                OnCREATEDChanged();
            }
        }
        private global::System.DateTime _CREATED;
        partial void OnCREATEDChanging(global::System.DateTime value);
        partial void OnCREATEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MODIFIED
        {
            get
            {
                return _MODIFIED;
            }
            set
            {
                OnMODIFIEDChanging(value);
                ReportPropertyChanging("MODIFIED");
                _MODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MODIFIED");
                OnMODIFIEDChanged();
            }
        }
        private Nullable<global::System.DateTime> _MODIFIED;
        partial void OnMODIFIEDChanging(Nullable<global::System.DateTime> value);
        partial void OnMODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SHARED
        {
            get
            {
                return _SHARED;
            }
            set
            {
                OnSHAREDChanging(value);
                ReportPropertyChanging("SHARED");
                _SHARED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHARED");
                OnSHAREDChanged();
            }
        }
        private Nullable<global::System.DateTime> _SHARED;
        partial void OnSHAREDChanging(Nullable<global::System.DateTime> value);
        partial void OnSHAREDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERDATA
        {
            get
            {
                return _USERDATA;
            }
            set
            {
                OnUSERDATAChanging(value);
                ReportPropertyChanging("USERDATA");
                _USERDATA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERDATA");
                OnUSERDATAChanged();
            }
        }
        private global::System.String _USERDATA;
        partial void OnUSERDATAChanging(global::System.String value);
        partial void OnUSERDATAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VIEWORDER
        {
            get
            {
                return _VIEWORDER;
            }
            set
            {
                OnVIEWORDERChanging(value);
                ReportPropertyChanging("VIEWORDER");
                _VIEWORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VIEWORDER");
                OnVIEWORDERChanged();
            }
        }
        private Nullable<global::System.Int32> _VIEWORDER;
        partial void OnVIEWORDERChanging(Nullable<global::System.Int32> value);
        partial void OnVIEWORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GROUPORDER
        {
            get
            {
                return _GROUPORDER;
            }
            set
            {
                OnGROUPORDERChanging(value);
                ReportPropertyChanging("GROUPORDER");
                _GROUPORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUPORDER");
                OnGROUPORDERChanged();
            }
        }
        private Nullable<global::System.Int32> _GROUPORDER;
        partial void OnGROUPORDERChanging(Nullable<global::System.Int32> value);
        partial void OnGROUPORDERChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHBOARDDASHLET", "DASHLET")]
        public EntityCollection<DASHLET> DASHLET
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DASHLET>("Model.DASHBOARDDASHLET", "DASHLET");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DASHLET>("Model.DASHBOARDDASHLET", "DASHLET", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="DASHLET")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DASHLET : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DASHLET object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="dASHBOARDID">Initial value of the DASHBOARDID property.</param>
        /// <param name="dASHLETMODULEID">Initial value of the DASHLETMODULEID property.</param>
        /// <param name="pOSITION">Initial value of the POSITION property.</param>
        /// <param name="cREATEDBY">Initial value of the CREATEDBY property.</param>
        /// <param name="cREATED">Initial value of the CREATED property.</param>
        public static DASHLET CreateDASHLET(global::System.Int32 id, global::System.Int32 dASHBOARDID, global::System.Int32 dASHLETMODULEID, global::System.String pOSITION, global::System.String cREATEDBY, global::System.DateTime cREATED)
        {
            DASHLET dASHLET = new DASHLET();
            dASHLET.ID = id;
            dASHLET.DASHBOARDID = dASHBOARDID;
            dASHLET.DASHLETMODULEID = dASHLETMODULEID;
            dASHLET.POSITION = pOSITION;
            dASHLET.CREATEDBY = cREATEDBY;
            dASHLET.CREATED = cREATED;
            return dASHLET;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DASHBOARDID
        {
            get
            {
                return _DASHBOARDID;
            }
            set
            {
                OnDASHBOARDIDChanging(value);
                ReportPropertyChanging("DASHBOARDID");
                _DASHBOARDID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DASHBOARDID");
                OnDASHBOARDIDChanged();
            }
        }
        private global::System.Int32 _DASHBOARDID;
        partial void OnDASHBOARDIDChanging(global::System.Int32 value);
        partial void OnDASHBOARDIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DASHLETMODULEID
        {
            get
            {
                return _DASHLETMODULEID;
            }
            set
            {
                OnDASHLETMODULEIDChanging(value);
                ReportPropertyChanging("DASHLETMODULEID");
                _DASHLETMODULEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DASHLETMODULEID");
                OnDASHLETMODULEIDChanged();
            }
        }
        private global::System.Int32 _DASHLETMODULEID;
        partial void OnDASHLETMODULEIDChanging(global::System.Int32 value);
        partial void OnDASHLETMODULEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONFIG
        {
            get
            {
                return _CONFIG;
            }
            set
            {
                OnCONFIGChanging(value);
                ReportPropertyChanging("CONFIG");
                _CONFIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONFIG");
                OnCONFIGChanged();
            }
        }
        private global::System.String _CONFIG;
        partial void OnCONFIGChanging(global::System.String value);
        partial void OnCONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PANECONFIG
        {
            get
            {
                return _PANECONFIG;
            }
            set
            {
                OnPANECONFIGChanging(value);
                ReportPropertyChanging("PANECONFIG");
                _PANECONFIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PANECONFIG");
                OnPANECONFIGChanged();
            }
        }
        private global::System.String _PANECONFIG;
        partial void OnPANECONFIGChanging(global::System.String value);
        partial void OnPANECONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String POSITION
        {
            get
            {
                return _POSITION;
            }
            set
            {
                OnPOSITIONChanging(value);
                ReportPropertyChanging("POSITION");
                _POSITION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("POSITION");
                OnPOSITIONChanged();
            }
        }
        private global::System.String _POSITION;
        partial void OnPOSITIONChanging(global::System.String value);
        partial void OnPOSITIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STYLE
        {
            get
            {
                return _STYLE;
            }
            set
            {
                OnSTYLEChanging(value);
                ReportPropertyChanging("STYLE");
                _STYLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STYLE");
                OnSTYLEChanged();
            }
        }
        private global::System.String _STYLE;
        partial void OnSTYLEChanging(global::System.String value);
        partial void OnSTYLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLS
        {
            get
            {
                return _CLS;
            }
            set
            {
                OnCLSChanging(value);
                ReportPropertyChanging("CLS");
                _CLS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLS");
                OnCLSChanged();
            }
        }
        private global::System.String _CLS;
        partial void OnCLSChanging(global::System.String value);
        partial void OnCLSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTR
        {
            get
            {
                return _ATTR;
            }
            set
            {
                OnATTRChanging(value);
                ReportPropertyChanging("ATTR");
                _ATTR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTR");
                OnATTRChanged();
            }
        }
        private global::System.String _ATTR;
        partial void OnATTRChanging(global::System.String value);
        partial void OnATTRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUPNAME
        {
            get
            {
                return _GROUPNAME;
            }
            set
            {
                OnGROUPNAMEChanging(value);
                ReportPropertyChanging("GROUPNAME");
                _GROUPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUPNAME");
                OnGROUPNAMEChanged();
            }
        }
        private global::System.String _GROUPNAME;
        partial void OnGROUPNAMEChanging(global::System.String value);
        partial void OnGROUPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEDBY
        {
            get
            {
                return _CREATEDBY;
            }
            set
            {
                OnCREATEDBYChanging(value);
                ReportPropertyChanging("CREATEDBY");
                _CREATEDBY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEDBY");
                OnCREATEDBYChanged();
            }
        }
        private global::System.String _CREATEDBY;
        partial void OnCREATEDBYChanging(global::System.String value);
        partial void OnCREATEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODIFIEDBY
        {
            get
            {
                return _MODIFIEDBY;
            }
            set
            {
                OnMODIFIEDBYChanging(value);
                ReportPropertyChanging("MODIFIEDBY");
                _MODIFIEDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODIFIEDBY");
                OnMODIFIEDBYChanged();
            }
        }
        private global::System.String _MODIFIEDBY;
        partial void OnMODIFIEDBYChanging(global::System.String value);
        partial void OnMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHAREDBY
        {
            get
            {
                return _SHAREDBY;
            }
            set
            {
                OnSHAREDBYChanging(value);
                ReportPropertyChanging("SHAREDBY");
                _SHAREDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHAREDBY");
                OnSHAREDBYChanged();
            }
        }
        private global::System.String _SHAREDBY;
        partial void OnSHAREDBYChanging(global::System.String value);
        partial void OnSHAREDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED
        {
            get
            {
                return _CREATED;
            }
            set
            {
                OnCREATEDChanging(value);
                ReportPropertyChanging("CREATED");
                _CREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED");
                OnCREATEDChanged();
            }
        }
        private global::System.DateTime _CREATED;
        partial void OnCREATEDChanging(global::System.DateTime value);
        partial void OnCREATEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MODIFIED
        {
            get
            {
                return _MODIFIED;
            }
            set
            {
                OnMODIFIEDChanging(value);
                ReportPropertyChanging("MODIFIED");
                _MODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MODIFIED");
                OnMODIFIEDChanged();
            }
        }
        private Nullable<global::System.DateTime> _MODIFIED;
        partial void OnMODIFIEDChanging(Nullable<global::System.DateTime> value);
        partial void OnMODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SHARED
        {
            get
            {
                return _SHARED;
            }
            set
            {
                OnSHAREDChanging(value);
                ReportPropertyChanging("SHARED");
                _SHARED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHARED");
                OnSHAREDChanged();
            }
        }
        private Nullable<global::System.DateTime> _SHARED;
        partial void OnSHAREDChanging(Nullable<global::System.DateTime> value);
        partial void OnSHAREDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERDATA
        {
            get
            {
                return _USERDATA;
            }
            set
            {
                OnUSERDATAChanging(value);
                ReportPropertyChanging("USERDATA");
                _USERDATA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERDATA");
                OnUSERDATAChanged();
            }
        }
        private global::System.String _USERDATA;
        partial void OnUSERDATAChanging(global::System.String value);
        partial void OnUSERDATAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHBOARDDASHLET", "DASHBOARD")]
        public DASHBOARD DASHBOARD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DASHBOARD>("Model.DASHBOARDDASHLET", "DASHBOARD").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DASHBOARD>("Model.DASHBOARDDASHLET", "DASHBOARD").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DASHBOARD> DASHBOARDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DASHBOARD>("Model.DASHBOARDDASHLET", "DASHBOARD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DASHBOARD>("Model.DASHBOARDDASHLET", "DASHBOARD", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLETMODULEDASHLET", "DASHLETMODULE")]
        public DASHLETMODULE DASHLETMODULE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DASHLETMODULE>("Model.DASHLETMODULEDASHLET", "DASHLETMODULE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DASHLETMODULE>("Model.DASHLETMODULEDASHLET", "DASHLETMODULE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DASHLETMODULE> DASHLETMODULEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DASHLETMODULE>("Model.DASHLETMODULEDASHLET", "DASHLETMODULE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DASHLETMODULE>("Model.DASHLETMODULEDASHLET", "DASHLETMODULE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="DASHLETMODULE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DASHLETMODULE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DASHLETMODULE object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="pATH">Initial value of the PATH property.</param>
        /// <param name="tITLE">Initial value of the TITLE property.</param>
        /// <param name="cONFIG">Initial value of the CONFIG property.</param>
        /// <param name="pANECONFIG">Initial value of the PANECONFIG property.</param>
        /// <param name="dASHLETCONFIG">Initial value of the DASHLETCONFIG property.</param>
        /// <param name="cREATEDBY">Initial value of the CREATEDBY property.</param>
        /// <param name="cREATED">Initial value of the CREATED property.</param>
        public static DASHLETMODULE CreateDASHLETMODULE(global::System.Int32 id, global::System.String pATH, global::System.String tITLE, global::System.String cONFIG, global::System.String pANECONFIG, global::System.String dASHLETCONFIG, global::System.String cREATEDBY, global::System.DateTime cREATED)
        {
            DASHLETMODULE dASHLETMODULE = new DASHLETMODULE();
            dASHLETMODULE.ID = id;
            dASHLETMODULE.PATH = pATH;
            dASHLETMODULE.TITLE = tITLE;
            dASHLETMODULE.CONFIG = cONFIG;
            dASHLETMODULE.PANECONFIG = pANECONFIG;
            dASHLETMODULE.DASHLETCONFIG = dASHLETCONFIG;
            dASHLETMODULE.CREATEDBY = cREATEDBY;
            dASHLETMODULE.CREATED = cREATED;
            return dASHLETMODULE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PATH
        {
            get
            {
                return _PATH;
            }
            set
            {
                OnPATHChanging(value);
                ReportPropertyChanging("PATH");
                _PATH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PATH");
                OnPATHChanged();
            }
        }
        private global::System.String _PATH;
        partial void OnPATHChanging(global::System.String value);
        partial void OnPATHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONFIG
        {
            get
            {
                return _CONFIG;
            }
            set
            {
                OnCONFIGChanging(value);
                ReportPropertyChanging("CONFIG");
                _CONFIG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CONFIG");
                OnCONFIGChanged();
            }
        }
        private global::System.String _CONFIG;
        partial void OnCONFIGChanging(global::System.String value);
        partial void OnCONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PANECONFIG
        {
            get
            {
                return _PANECONFIG;
            }
            set
            {
                OnPANECONFIGChanging(value);
                ReportPropertyChanging("PANECONFIG");
                _PANECONFIG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PANECONFIG");
                OnPANECONFIGChanged();
            }
        }
        private global::System.String _PANECONFIG;
        partial void OnPANECONFIGChanging(global::System.String value);
        partial void OnPANECONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DASHLETCONFIG
        {
            get
            {
                return _DASHLETCONFIG;
            }
            set
            {
                OnDASHLETCONFIGChanging(value);
                ReportPropertyChanging("DASHLETCONFIG");
                _DASHLETCONFIG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DASHLETCONFIG");
                OnDASHLETCONFIGChanged();
            }
        }
        private global::System.String _DASHLETCONFIG;
        partial void OnDASHLETCONFIGChanging(global::System.String value);
        partial void OnDASHLETCONFIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STYLE
        {
            get
            {
                return _STYLE;
            }
            set
            {
                OnSTYLEChanging(value);
                ReportPropertyChanging("STYLE");
                _STYLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STYLE");
                OnSTYLEChanged();
            }
        }
        private global::System.String _STYLE;
        partial void OnSTYLEChanging(global::System.String value);
        partial void OnSTYLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLS
        {
            get
            {
                return _CLS;
            }
            set
            {
                OnCLSChanging(value);
                ReportPropertyChanging("CLS");
                _CLS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLS");
                OnCLSChanged();
            }
        }
        private global::System.String _CLS;
        partial void OnCLSChanging(global::System.String value);
        partial void OnCLSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTR
        {
            get
            {
                return _ATTR;
            }
            set
            {
                OnATTRChanging(value);
                ReportPropertyChanging("ATTR");
                _ATTR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTR");
                OnATTRChanged();
            }
        }
        private global::System.String _ATTR;
        partial void OnATTRChanging(global::System.String value);
        partial void OnATTRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEDBY
        {
            get
            {
                return _CREATEDBY;
            }
            set
            {
                OnCREATEDBYChanging(value);
                ReportPropertyChanging("CREATEDBY");
                _CREATEDBY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEDBY");
                OnCREATEDBYChanged();
            }
        }
        private global::System.String _CREATEDBY;
        partial void OnCREATEDBYChanging(global::System.String value);
        partial void OnCREATEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODIFIEDBY
        {
            get
            {
                return _MODIFIEDBY;
            }
            set
            {
                OnMODIFIEDBYChanging(value);
                ReportPropertyChanging("MODIFIEDBY");
                _MODIFIEDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODIFIEDBY");
                OnMODIFIEDBYChanged();
            }
        }
        private global::System.String _MODIFIEDBY;
        partial void OnMODIFIEDBYChanging(global::System.String value);
        partial void OnMODIFIEDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHAREDBY
        {
            get
            {
                return _SHAREDBY;
            }
            set
            {
                OnSHAREDBYChanging(value);
                ReportPropertyChanging("SHAREDBY");
                _SHAREDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHAREDBY");
                OnSHAREDBYChanged();
            }
        }
        private global::System.String _SHAREDBY;
        partial void OnSHAREDBYChanging(global::System.String value);
        partial void OnSHAREDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED
        {
            get
            {
                return _CREATED;
            }
            set
            {
                OnCREATEDChanging(value);
                ReportPropertyChanging("CREATED");
                _CREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED");
                OnCREATEDChanged();
            }
        }
        private global::System.DateTime _CREATED;
        partial void OnCREATEDChanging(global::System.DateTime value);
        partial void OnCREATEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MODIFIED
        {
            get
            {
                return _MODIFIED;
            }
            set
            {
                OnMODIFIEDChanging(value);
                ReportPropertyChanging("MODIFIED");
                _MODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MODIFIED");
                OnMODIFIEDChanged();
            }
        }
        private Nullable<global::System.DateTime> _MODIFIED;
        partial void OnMODIFIEDChanging(Nullable<global::System.DateTime> value);
        partial void OnMODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SHARED
        {
            get
            {
                return _SHARED;
            }
            set
            {
                OnSHAREDChanging(value);
                ReportPropertyChanging("SHARED");
                _SHARED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHARED");
                OnSHAREDChanged();
            }
        }
        private Nullable<global::System.DateTime> _SHARED;
        partial void OnSHAREDChanging(Nullable<global::System.DateTime> value);
        partial void OnSHAREDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUPNAME
        {
            get
            {
                return _GROUPNAME;
            }
            set
            {
                OnGROUPNAMEChanging(value);
                ReportPropertyChanging("GROUPNAME");
                _GROUPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUPNAME");
                OnGROUPNAMEChanged();
            }
        }
        private global::System.String _GROUPNAME;
        partial void OnGROUPNAMEChanging(global::System.String value);
        partial void OnGROUPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERDATA
        {
            get
            {
                return _USERDATA;
            }
            set
            {
                OnUSERDATAChanging(value);
                ReportPropertyChanging("USERDATA");
                _USERDATA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERDATA");
                OnUSERDATAChanged();
            }
        }
        private global::System.String _USERDATA;
        partial void OnUSERDATAChanging(global::System.String value);
        partial void OnUSERDATAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VIEWORDER
        {
            get
            {
                return _VIEWORDER;
            }
            set
            {
                OnVIEWORDERChanging(value);
                ReportPropertyChanging("VIEWORDER");
                _VIEWORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VIEWORDER");
                OnVIEWORDERChanged();
            }
        }
        private Nullable<global::System.Int32> _VIEWORDER;
        partial void OnVIEWORDERChanging(Nullable<global::System.Int32> value);
        partial void OnVIEWORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GROUPORDER
        {
            get
            {
                return _GROUPORDER;
            }
            set
            {
                OnGROUPORDERChanging(value);
                ReportPropertyChanging("GROUPORDER");
                _GROUPORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUPORDER");
                OnGROUPORDERChanged();
            }
        }
        private Nullable<global::System.Int32> _GROUPORDER;
        partial void OnGROUPORDERChanging(Nullable<global::System.Int32> value);
        partial void OnGROUPORDERChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DASHLETMODULEDASHLET", "DASHLET")]
        public EntityCollection<DASHLET> DASHLET
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DASHLET>("Model.DASHLETMODULEDASHLET", "DASHLET");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DASHLET>("Model.DASHLETMODULEDASHLET", "DASHLET", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ENTITYAUTH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ENTITYAUTH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ENTITYAUTH object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="eNTITYTYPE">Initial value of the ENTITYTYPE property.</param>
        /// <param name="eNTITYID">Initial value of the ENTITYID property.</param>
        /// <param name="rOLEORUSER">Initial value of the ROLEORUSER property.</param>
        /// <param name="pERMISSION">Initial value of the PERMISSION property.</param>
        /// <param name="aUTHTYPE">Initial value of the AUTHTYPE property.</param>
        public static ENTITYAUTH CreateENTITYAUTH(global::System.Int32 id, global::System.String eNTITYTYPE, global::System.Int32 eNTITYID, global::System.String rOLEORUSER, global::System.String pERMISSION, global::System.String aUTHTYPE)
        {
            ENTITYAUTH eNTITYAUTH = new ENTITYAUTH();
            eNTITYAUTH.ID = id;
            eNTITYAUTH.ENTITYTYPE = eNTITYTYPE;
            eNTITYAUTH.ENTITYID = eNTITYID;
            eNTITYAUTH.ROLEORUSER = rOLEORUSER;
            eNTITYAUTH.PERMISSION = pERMISSION;
            eNTITYAUTH.AUTHTYPE = aUTHTYPE;
            return eNTITYAUTH;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ENTITYTYPE
        {
            get
            {
                return _ENTITYTYPE;
            }
            set
            {
                OnENTITYTYPEChanging(value);
                ReportPropertyChanging("ENTITYTYPE");
                _ENTITYTYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ENTITYTYPE");
                OnENTITYTYPEChanged();
            }
        }
        private global::System.String _ENTITYTYPE;
        partial void OnENTITYTYPEChanging(global::System.String value);
        partial void OnENTITYTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ENTITYID
        {
            get
            {
                return _ENTITYID;
            }
            set
            {
                OnENTITYIDChanging(value);
                ReportPropertyChanging("ENTITYID");
                _ENTITYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ENTITYID");
                OnENTITYIDChanged();
            }
        }
        private global::System.Int32 _ENTITYID;
        partial void OnENTITYIDChanging(global::System.Int32 value);
        partial void OnENTITYIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ROLEORUSER
        {
            get
            {
                return _ROLEORUSER;
            }
            set
            {
                OnROLEORUSERChanging(value);
                ReportPropertyChanging("ROLEORUSER");
                _ROLEORUSER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ROLEORUSER");
                OnROLEORUSERChanged();
            }
        }
        private global::System.String _ROLEORUSER;
        partial void OnROLEORUSERChanging(global::System.String value);
        partial void OnROLEORUSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PERMISSION
        {
            get
            {
                return _PERMISSION;
            }
            set
            {
                OnPERMISSIONChanging(value);
                ReportPropertyChanging("PERMISSION");
                _PERMISSION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PERMISSION");
                OnPERMISSIONChanged();
            }
        }
        private global::System.String _PERMISSION;
        partial void OnPERMISSIONChanging(global::System.String value);
        partial void OnPERMISSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AUTHTYPE
        {
            get
            {
                return _AUTHTYPE;
            }
            set
            {
                OnAUTHTYPEChanging(value);
                ReportPropertyChanging("AUTHTYPE");
                _AUTHTYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AUTHTYPE");
                OnAUTHTYPEChanged();
            }
        }
        private global::System.String _AUTHTYPE;
        partial void OnAUTHTYPEChanging(global::System.String value);
        partial void OnAUTHTYPEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TAG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TAG object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tAGNAME">Initial value of the TAGNAME property.</param>
        public static TAG CreateTAG(global::System.Int32 id, global::System.String tAGNAME)
        {
            TAG tAG = new TAG();
            tAG.ID = id;
            tAG.TAGNAME = tAGNAME;
            return tAG;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAGNAME
        {
            get
            {
                return _TAGNAME;
            }
            set
            {
                OnTAGNAMEChanging(value);
                ReportPropertyChanging("TAGNAME");
                _TAGNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TAGNAME");
                OnTAGNAMEChanged();
            }
        }
        private global::System.String _TAGNAME;
        partial void OnTAGNAMEChanging(global::System.String value);
        partial void OnTAGNAMEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "TAGTAGRELATION", "TAGRELATION")]
        public EntityCollection<TAGRELATION> TAGRELATION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TAGRELATION>("Model.TAGTAGRELATION", "TAGRELATION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TAGRELATION>("Model.TAGTAGRELATION", "TAGRELATION", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TAGRELATION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAGRELATION : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TAGRELATION object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tAGID">Initial value of the TAGID property.</param>
        /// <param name="cONTROLID">Initial value of the CONTROLID property.</param>
        /// <param name="cONTROLLER">Initial value of the CONTROLLER property.</param>
        public static TAGRELATION CreateTAGRELATION(global::System.Int32 id, global::System.Int32 tAGID, global::System.Int32 cONTROLID, global::System.String cONTROLLER)
        {
            TAGRELATION tAGRELATION = new TAGRELATION();
            tAGRELATION.ID = id;
            tAGRELATION.TAGID = tAGID;
            tAGRELATION.CONTROLID = cONTROLID;
            tAGRELATION.CONTROLLER = cONTROLLER;
            return tAGRELATION;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TAGID
        {
            get
            {
                return _TAGID;
            }
            set
            {
                OnTAGIDChanging(value);
                ReportPropertyChanging("TAGID");
                _TAGID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAGID");
                OnTAGIDChanged();
            }
        }
        private global::System.Int32 _TAGID;
        partial void OnTAGIDChanging(global::System.Int32 value);
        partial void OnTAGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CONTROLID
        {
            get
            {
                return _CONTROLID;
            }
            set
            {
                OnCONTROLIDChanging(value);
                ReportPropertyChanging("CONTROLID");
                _CONTROLID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CONTROLID");
                OnCONTROLIDChanged();
            }
        }
        private global::System.Int32 _CONTROLID;
        partial void OnCONTROLIDChanging(global::System.Int32 value);
        partial void OnCONTROLIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONTROLLER
        {
            get
            {
                return _CONTROLLER;
            }
            set
            {
                OnCONTROLLERChanging(value);
                ReportPropertyChanging("CONTROLLER");
                _CONTROLLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CONTROLLER");
                OnCONTROLLERChanged();
            }
        }
        private global::System.String _CONTROLLER;
        partial void OnCONTROLLERChanging(global::System.String value);
        partial void OnCONTROLLERChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "TAGTAGRELATION", "TAG")]
        public TAG TAG
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAG>("Model.TAGTAGRELATION", "TAG").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAG>("Model.TAGTAGRELATION", "TAG").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TAG> TAGReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAG>("Model.TAGTAGRELATION", "TAG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TAG>("Model.TAGTAGRELATION", "TAG", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
