//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDash.Webform.Management.Controls.Dashboard {
    
    
    public partial class DashboardEditor {
        
        /// <summary>
        /// dashboarEditorModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboarEditorModal;
        
        /// <summary>
        /// Localize1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize1;
        
        /// <summary>
        /// Localize2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize2;
        
        /// <summary>
        /// Localize4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize4;
        
        /// <summary>
        /// Localize3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize3;
        
        /// <summary>
        /// ctlAuthentication control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize ctlAuthentication;
        
        /// <summary>
        /// ctlDashboardEditorActiveTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ctlDashboardEditorActiveTab;
        
        /// <summary>
        /// ctlTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlTitle;
        
        /// <summary>
        /// ctlDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlDescription;
        
        /// <summary>
        /// ctlType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledDropDown ctlType;
        
        /// <summary>
        /// ctlMetadata control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlMetadata;
        
        /// <summary>
        /// ctlLayout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlLayout;
        
        /// <summary>
        /// ctlPaneConfig control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlPaneConfig;
        
        /// <summary>
        /// ctlConfig control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlConfig;
        
        /// <summary>
        /// ctlAuthenticationEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Controls.Common.AuthenticationEditor ctlAuthenticationEditor;
        
        /// <summary>
        /// ctlCancelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashButton ctlCancelButton;
        
        /// <summary>
        /// ctlSubmitButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashButton ctlSubmitButton;
    }
}
