//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Dashlet.
        /// </summary>
        internal static string AddDashlet {
            get {
                return ResourceManager.GetString("AddDashlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2009 - 2013 Kalitte Inc. All rights reserved..
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Step: Data Source and Chart Type.
        /// </summary>
        internal static string ChartDataDashletStep1 {
            get {
                return ResourceManager.GetString("ChartDataDashletStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source provides measures, dimensions and data values that are required for analysis..
        /// </summary>
        internal static string ChartDataDashletStep1Desc {
            get {
                return ResourceManager.GetString("ChartDataDashletStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Step: Measures.
        /// </summary>
        internal static string ChartDataDashletStep2 {
            get {
                return ResourceManager.GetString("ChartDataDashletStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric is a numerical value propery that allows analytical calculations..
        /// </summary>
        internal static string ChartDataDashletStep2Desc {
            get {
                return ResourceManager.GetString("ChartDataDashletStep2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3th Step: Dimensions and Sorting.
        /// </summary>
        internal static string ChartDataDashletStep3 {
            get {
                return ResourceManager.GetString("ChartDataDashletStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension groups metric value calculations.&lt;br&gt;
        ///Pivot data dimension creates series in your chart view..
        /// </summary>
        internal static string ChartDataDashletStep3Desc {
            get {
                return ResourceManager.GetString("ChartDataDashletStep3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Step: Chart Display.
        /// </summary>
        internal static string ChartDataDashletStep4 {
            get {
                return ResourceManager.GetString("ChartDataDashletStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change look and feel of chart. Use chart types for different visual perspectives..
        /// </summary>
        internal static string ChartDataDashletStep4Desc {
            get {
                return ResourceManager.GetString("ChartDataDashletStep4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th Step: Chart Labels.
        /// </summary>
        internal static string ChartDataDashletStep5 {
            get {
                return ResourceManager.GetString("ChartDataDashletStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom labels over chart to provide additional information..
        /// </summary>
        internal static string ChartDataDashletStep5Desc {
            get {
                return ResourceManager.GetString("ChartDataDashletStep5Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Height (i.e. 300).
        /// </summary>
        internal static string ChartHeight {
            get {
                return ResourceManager.GetString("ChartHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Theme.
        /// </summary>
        internal static string ChartTheme {
            get {
                return ResourceManager.GetString("ChartTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string ChartThemeBlue {
            get {
                return ResourceManager.GetString("ChartThemeBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string ChartThemeBlue1 {
            get {
                return ResourceManager.GetString("ChartThemeBlue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ChartThemeDefault {
            get {
                return ResourceManager.GetString("ChartThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ChartThemeDefault1 {
            get {
                return ResourceManager.GetString("ChartThemeDefault1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string ChartThemeGray {
            get {
                return ResourceManager.GetString("ChartThemeGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string ChartThemeGray1 {
            get {
                return ResourceManager.GetString("ChartThemeGray1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string ChartThemeGreen {
            get {
                return ResourceManager.GetString("ChartThemeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string ChartThemeGreen1 {
            get {
                return ResourceManager.GetString("ChartThemeGreen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Chart.
        /// </summary>
        internal static string ChartTypeArea {
            get {
                return ResourceManager.GetString("ChartTypeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Chart.
        /// </summary>
        internal static string ChartTypeBar {
            get {
                return ResourceManager.GetString("ChartTypeBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chart.
        /// </summary>
        internal static string ChartTypeColumn {
            get {
                return ResourceManager.GetString("ChartTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Chart.
        /// </summary>
        internal static string ChartTypeLine {
            get {
                return ResourceManager.GetString("ChartTypeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Chart.
        /// </summary>
        internal static string ChartTypePie {
            get {
                return ResourceManager.GetString("ChartTypePie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Dashboard.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Css Class.
        /// </summary>
        internal static string CssClass {
            get {
                return ResourceManager.GetString("CssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Dimension.
        /// </summary>
        internal static string FirstDimension {
            get {
                return ResourceManager.GetString("FirstDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Metric.
        /// </summary>
        internal static string FirstMetric {
            get {
                return ResourceManager.GetString("FirstMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit &lt;a href=&quot;http://www.jdash.net&quot; target=&quot;_blank&quot;&gt;www.jdash.net&lt;/a&gt; for licensing options..
        /// </summary>
        internal static string FooterLink {
            get {
                return ResourceManager.GetString("FooterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FooterText.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Text.
        /// </summary>
        internal static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit data by:.
        /// </summary>
        internal static string LimtDataBy {
            get {
                return ResourceManager.GetString("LimtDataBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        internal static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Rows.
        /// </summary>
        internal static string NRows {
            get {
                return ResourceManager.GetString("NRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online demo - JDash.Net - Asp.Net based dashboard and widget toolkit.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        internal static string Pie {
            get {
                return ResourceManager.GetString("Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot Data.
        /// </summary>
        internal static string PivotData {
            get {
                return ResourceManager.GetString("PivotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        internal static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Step.
        /// </summary>
        internal static string PreviousStep {
            get {
                return ResourceManager.GetString("PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Dimension (Optional).
        /// </summary>
        internal static string SecondDimensionOptional {
            get {
                return ResourceManager.GetString("SecondDimensionOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Metric (Optional).
        /// </summary>
        internal static string SecondMetricOptional {
            get {
                return ResourceManager.GetString("SecondMetricOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select chart type.
        /// </summary>
        internal static string SelectChartType {
            get {
                return ResourceManager.GetString("SelectChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a data set to analyse.
        /// </summary>
        internal static string SelectCube {
            get {
                return ResourceManager.GetString("SelectCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group metrics by following dimensions:.
        /// </summary>
        internal static string SelectDimensions {
            get {
                return ResourceManager.GetString("SelectDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a metric.
        /// </summary>
        internal static string SelectMetric {
            get {
                return ResourceManager.GetString("SelectMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select metrics you want to see:.
        /// </summary>
        internal static string SelectMetrics {
            get {
                return ResourceManager.GetString("SelectMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip top N rows.
        /// </summary>
        internal static string SkipTopNRows {
            get {
                return ResourceManager.GetString("SkipTopNRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort data by:.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing or decreasing?.
        /// </summary>
        internal static string SortDir {
            get {
                return ResourceManager.GetString("SortDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then by:.
        /// </summary>
        internal static string SortThenBy {
            get {
                return ResourceManager.GetString("SortThenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Step: Data Source.
        /// </summary>
        internal static string TableDataDashletStep1 {
            get {
                return ResourceManager.GetString("TableDataDashletStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source provides measures, dimensions and data values that are required for analysis..
        /// </summary>
        internal static string TableDataDashletStep1Desc {
            get {
                return ResourceManager.GetString("TableDataDashletStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Step: Measures.
        /// </summary>
        internal static string TableDataDashletStep2 {
            get {
                return ResourceManager.GetString("TableDataDashletStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric is a numerical value propery that allows analytical calculations. .
        /// </summary>
        internal static string TableDataDashletStep2Desc {
            get {
                return ResourceManager.GetString("TableDataDashletStep2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3th Step: Dimensions.
        /// </summary>
        internal static string TableDataDashletStep3 {
            get {
                return ResourceManager.GetString("TableDataDashletStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension groups metric value calculations..
        /// </summary>
        internal static string TableDataDashletStep3Desc {
            get {
                return ResourceManager.GetString("TableDataDashletStep3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Step: Order and Limit.
        /// </summary>
        internal static string TableDataDashletStep4 {
            get {
                return ResourceManager.GetString("TableDataDashletStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re order and limit data for a better result display..
        /// </summary>
        internal static string TableDataDashletStep4Desc {
            get {
                return ResourceManager.GetString("TableDataDashletStep4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
