//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDash.Webform.Management.Controls.DashletModule {
    
    
    public partial class DashletCommandEditor {
        
        /// <summary>
        /// CommandEditorModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CommandEditorModal;
        
        /// <summary>
        /// Localize1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize1;
        
        /// <summary>
        /// ctlName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlName;
        
        /// <summary>
        /// ctlLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlLabel;
        
        /// <summary>
        /// ctlCssClass control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlCssClass;
        
        /// <summary>
        /// ctlTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlTitle;
        
        /// <summary>
        /// ctlConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashChekBoxGroup ctlConfirm;
        
        /// <summary>
        /// ctlConfirmMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledTextBox ctlConfirmMessage;
        
        /// <summary>
        /// ctlType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashLabeledDropDown ctlType;
        
        /// <summary>
        /// ctlNotifyOnCommand control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashChekBoxGroup ctlNotifyOnCommand;
        
        /// <summary>
        /// ctlSubmitButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashButton ctlSubmitButton;
        
        /// <summary>
        /// ctlCancelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JDash.Webform.Management.Core.Controls.UI.JDashButton ctlCancelButton;
    }
}
