define("jdash/nls/language", {
    root: {
        Ok:"Ok",
        Yes:"Yes",
        No:"No",
        Cancel:"Cancel",
        Accept:"Accept",
        Decline:"Decline",
        Error:"Error",
        Warning:"Warning",
        Information:"Information",
        Confirmation: "Confirmation",
        Maximize: "Maximize",
        Collapse: "Collapse",
        Restore: "Restore",
        Remove: "Remove",
        Seperator: "Seperator",
        Share: "Share",
        About: "About",
        EditSettings: "Settings",
        Options: "Options",
        MakeSticky: "Make Sticky",
        MakeUnsticky: "Make UnSticky",
        Reload: "Reload",
        RetreivingContent: "Retreiving content",
        Save: "Save",
        Apply: "Apply",
        Cancel: "Cancel",
        ViewMode: "View Mode",
        InsideIFrame: "Inside IFrame",
        InsideCurrentDocument: "Inside Current Document",
        InvalidRSSSource: "Invalid RSS Source!",
        ValidatingRSSContent: "Validating RSS content ...",
        ShowHeadersOnly: "Show headers only",
        ShowFullContent: "Show full content",
        ShowContentSummary: "Show content summary",
        LimitFeeds: "Limit Feeds",
        Unlimited: "Unlimited",
        Refresh: "Refresh",
        StartingDashboardLoad: "Loading dashboard...",
        CreatingLayout: "Creating layout",
        RetreivingDashlets: "Retreiving dashlets",
        CreatingDashlets: "Creating Dashlets",
        DashletsCreated: "Dashlets created",
        StartingDashlets: "Starting dashlets",
        DashletsStarted: "Dashlets started",
        ChangePositions: "Change positions",
        SetBodyDrag: "Set Body Drag",
        SetHeaderDrag: "Set Header Drag",
        DisableTitleCollapse: "Disable title collapse",
        EnableTitleCollapse: "Enable title collapse",
        AllGroups: "All Groups",
        ConfirmMessage: "Are you sure?",
        ConfirmTitle: "Confirm",
        Others: "Others",
        UnableToLoad: "Can not load content!",
        FrameDimensions: "Frame Dimensions",
        Width: "Width",
        Heigth: "Heigth",
        UseDashboardTheme: "Use Dashboard Theme",
        Close: "Close",
        Clone: "Clone"
    },

    tr: true
});

